USE master
GO

CREATE DATABASE [JMS]
ON  PRIMARY 
( NAME = N'JMS', FILENAME = N'D:\RDSDBDATA\DATA\JMS.mdf' , SIZE = 100MB , FILEGROWTH = 10% )
LOG ON 
( NAME = N'JMS_log', FILENAME = N'D:\RDSDBDATA\DATA\JMS_log.ldf' , SIZE = 20MB , FILEGROWTH = 10%)
GO

--EXEC dbo.sp_dbcmptlevel @dbname=N'JMS', @new_cmptlevel=90
--GO
ALTER DATABASE [JMS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JMS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JMS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JMS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JMS] SET ARITHABORT OFF 
GO
ALTER DATABASE [JMS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [JMS] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [JMS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JMS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JMS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JMS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JMS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JMS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JMS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JMS] SET  READ_WRITE 
GO
ALTER DATABASE [JMS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [JMS] SET  MULTI_USER 
GO
ALTER DATABASE [JMS] SET PAGE_VERIFY CHECKSUM  
GO
USE [JMS]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [JMS] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
