USE [JMS];

DELETE FROM RFI;
DELETE FROM FILE_ACTION;
DELETE FROM JOB_DOC;
DELETE FROM JOB_ACTION;
DELETE FROM JOBS;
DELETE FROM FCA;
DELETE FROM BUILDING_CONTACT;
DELETE FROM BUILDING;
DELETE FROM ALARM_PANEL;
DELETE FROM SAP_HEADER;
DELETE FROM OWNER;
DELETE FROM KEY_RECEIPT;
DELETE FROM ASE_CONN;
DELETE FROM ASE_FILE;
DELETE FROM FILES;
DELETE FROM ADDRESS;
DELETE FROM CONTACT WHERE CONTACT_ID NOT IN (SELECT CONTACT_ID FROM USERS);
