USE [JMS];

--
-- DBVERSION
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.49', NULL);

--
-- ACTION_TYPE
--
SET IDENTITY_INSERT ACTION_TYPE ON
go
INSERT INTO ACTION_TYPE (ACTION_TYPE_ID, NAME) VALUES (1, 'Message'); -- 1
INSERT INTO ACTION_TYPE (ACTION_TYPE_ID, NAME) VALUES (2, 'Call'); -- 2
INSERT INTO ACTION_TYPE (ACTION_TYPE_ID, NAME) VALUES (3, 'Email'); -- 3
INSERT INTO ACTION_TYPE (ACTION_TYPE_ID, NAME) VALUES (4, 'Letter'); -- 4
INSERT INTO ACTION_TYPE (ACTION_TYPE_ID, NAME) VALUES (5, 'SMS'); -- 5
INSERT INTO ACTION_TYPE (ACTION_TYPE_ID, NAME) VALUES (6, 'Diary'); -- 6
INSERT INTO ACTION_TYPE (ACTION_TYPE_ID, NAME) VALUES (7, 'RFI'); -- 7
INSERT INTO ACTION_TYPE (ACTION_TYPE_ID, NAME) VALUES (8, 'File Status'); -- 8
INSERT INTO ACTION_TYPE (ACTION_TYPE_ID, NAME) VALUES (9, 'Job'); -- 9
INSERT INTO ACTION_TYPE (ACTION_TYPE_ID, NAME) VALUES (10, 'Job Close'); -- 10
go
SET IDENTITY_INSERT ACTION_TYPE OFF
go

--
-- ASE_CONN_TYPE
--
INSERT INTO ASE_CONN_TYPE (NAME) VALUES ('IP');
INSERT INTO ASE_CONN_TYPE (NAME) VALUES ('GPRS');
INSERT INTO ASE_CONN_TYPE (NAME) VALUES ('3G');
INSERT INTO ASE_CONN_TYPE (NAME) VALUES ('PSTN');
INSERT INTO ASE_CONN_TYPE (NAME) VALUES ('Radio');
INSERT INTO ASE_CONN_TYPE (NAME) VALUES ('Dial Up');

--
-- AUDIT_STATUS
--
INSERT INTO AUDIT_STATUS (AUDIT_STATUS_ID, NAME, DESCRIPTION) VALUES (1, 'ACTIVE', 'Active Audit');
INSERT INTO AUDIT_STATUS (AUDIT_STATUS_ID, NAME, DESCRIPTION) VALUES (2, 'APPROVED', 'Approved Audit');
INSERT INTO AUDIT_STATUS (AUDIT_STATUS_ID, NAME, DESCRIPTION) VALUES (3, 'REJECTED', 'Rejected Audit');

--
-- ASE_TYPE
--
INSERT INTO ASE_TYPE (NAME) VALUES ('ASE');

--
-- BUILDING_CONTACT_TYPE
--
INSERT INTO BUILDING_CONTACT_TYPE (NAME) VALUES ('Owner');
INSERT INTO BUILDING_CONTACT_TYPE (NAME) VALUES ('Daytime');
INSERT INTO BUILDING_CONTACT_TYPE (NAME) VALUES ('After Hours');
INSERT INTO BUILDING_CONTACT_TYPE (NAME) VALUES ('Security Company');
INSERT INTO BUILDING_CONTACT_TYPE (NAME) VALUES ('Fire Maintenence Company');

--
-- DOC_TYPE
--
INSERT INTO DOC_TYPE (NAME) VALUES ('Form');
INSERT INTO DOC_TYPE (NAME) VALUES ('Agree');
INSERT INTO DOC_TYPE (NAME) VALUES ('Letter');
INSERT INTO DOC_TYPE (NAME) VALUES ('Fax');
INSERT INTO DOC_TYPE (NAME) VALUES ('Email');
INSERT INTO DOC_TYPE (NAME) VALUES ('Report (xslt-fo)');
DELETE FROM DOC_TYPE WHERE DOC_TYPE_ID > 6;
SET IDENTITY_INSERT DOC_TYPE ON;
INSERT INTO DOC_TYPE (DOC_TYPE_ID, NAME) VALUES (7, 'Report (crystal)');
SET IDENTITY_INSERT DOC_TYPE OFF;

--
-- FILE_STATUS
--
INSERT INTO FILE_STATUS (FILE_STATUS_ID, NAME) VALUES (1, 'Connected');
INSERT INTO FILE_STATUS (FILE_STATUS_ID, NAME) VALUES (2, 'Disconnected');
INSERT INTO FILE_STATUS (FILE_STATUS_ID, NAME) VALUES (3, 'Archived');
INSERT INTO FILE_STATUS (FILE_STATUS_ID, NAME) VALUES (4, 'Pending');

--
-- FILE_TYPE
--
INSERT INTO FILE_TYPE (FILE_TYPE_ID, NAME) VALUES (1, 'ASE Key');
INSERT INTO FILE_TYPE (FILE_TYPE_ID, NAME) VALUES (2, 'Mail Register');

--
-- INVOICE_AREA
-- Main Invoicing Areas (CSO, TEM, RFS, MID ect)
--
INSERT INTO INVOICE_AREA (INVOICE_AREA_ID, NAME, DESCRIPTION) VALUES (1, 'CSO', 'CSO');
INSERT INTO INVOICE_AREA (INVOICE_AREA_ID, NAME, DESCRIPTION) VALUES (2, 'TEM', 'TEM');
INSERT INTO INVOICE_AREA (INVOICE_AREA_ID, NAME, DESCRIPTION) VALUES (3, 'RFS', 'RFS');
INSERT INTO INVOICE_AREA (INVOICE_AREA_ID, NAME, DESCRIPTION) VALUES (4, 'MID', 'MID');

--
-- INVOICE_TYPE
-- Invoice Types eg: Assessment, Inspection. Filter will old values B, S, N (BAO, SAO, NONE) to filter the invoice types based on selection
--
INSERT INTO INVOICE_TYPE (INVOICE_TYPE_ID, INVOICE_AREA_ID, NAME) VALUES (1, 1, 'Assessment');

--
-- JOB_TYPE
--
INSERT INTO JOB_TYPE (NAME) VALUES ('Data');
INSERT INTO JOB_TYPE (NAME) VALUES ('Fault');
INSERT INTO JOB_TYPE (NAME) VALUES ('Alarm Connection');
INSERT INTO JOB_TYPE (NAME) VALUES ('Alarm Disconnection');
INSERT INTO JOB_TYPE (NAME) VALUES ('Alarm Transfer');

--
-- LEAVE_STATUS
--
INSERT INTO LEAVE_STATUS (NAME) VALUES ('Submitted');
INSERT INTO LEAVE_STATUS (NAME) VALUES ('Approved');
INSERT INTO LEAVE_STATUS (NAME) VALUES ('Declined');

--
-- LEAVE_TYPE
--
INSERT INTO LEAVE_TYPE (NAME) VALUES ('Annual Leave');
INSERT INTO LEAVE_TYPE (NAME) VALUES ('Carers Leave Unpaid');
INSERT INTO LEAVE_TYPE (NAME) VALUES ('Jury Duty');
INSERT INTO LEAVE_TYPE (NAME) VALUES ('Leave Without Pay');
INSERT INTO LEAVE_TYPE (NAME) VALUES ('Personal/Carers Leave Paid');
INSERT INTO LEAVE_TYPE (NAME) VALUES ('Study & Exam Leave');
INSERT INTO LEAVE_TYPE (NAME) VALUES ('Time in Lieu');

--
-- MAIL_BATCH_STATUS
--
INSERT INTO MAIL_BATCH_STATUS (MAIL_BATCH_STATUS_ID, NAME, DESCRIPTION) VALUES (1, 'SENT', 'Sent');
INSERT INTO MAIL_BATCH_STATUS (MAIL_BATCH_STATUS_ID, NAME, DESCRIPTION) VALUES (2, 'RECEIVED', 'Received');
INSERT INTO MAIL_BATCH_STATUS (MAIL_BATCH_STATUS_ID, NAME, DESCRIPTION) VALUES (3, 'REJECTED', 'Rejected');

--
-- MAIL_METHOD
--
INSERT INTO MAIL_METHOD (MAIL_METHOD_ID, NAME) VALUES (1, 'Email');
INSERT INTO MAIL_METHOD (MAIL_METHOD_ID, NAME) VALUES (2, 'Post');

--
-- MAIL_TYPE
--
INSERT INTO MAIL_TYPE (NAME) VALUES ('Standard');
INSERT INTO MAIL_TYPE (NAME) VALUES ('Express');

--
-- OWNER_TYPE
--
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID, NAME) VALUES (1, 'Owner');
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID, NAME) VALUES (2, 'Body Corporate');
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID, NAME) VALUES (3, 'Property Manager');
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID, NAME) VALUES (4, 'Tenant');
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID, NAME) VALUES (5, 'Alternate');

--
-- PAYMENT_METHOD
--
INSERT INTO PAYMENT_METHOD (PAYMENT_METHOD_ID, NAME) VALUES (1, 'Credit Card');
INSERT INTO PAYMENT_METHOD (PAYMENT_METHOD_ID, NAME) VALUES (2, 'Purchase Order');
INSERT INTO PAYMENT_METHOD (PAYMENT_METHOD_ID, NAME) VALUES (3, 'Cheque');
INSERT INTO PAYMENT_METHOD (PAYMENT_METHOD_ID, NAME) VALUES (4, 'BPay');

--
-- REGION (set identity to start with 1)
--
INSERT INTO REGION (NAME) VALUES ('Northern Region');
INSERT INTO REGION (NAME) VALUES ('Central Region');
INSERT INTO REGION (NAME) VALUES ('South West');
INSERT INTO REGION (NAME) VALUES ('North Coast');
INSERT INTO REGION (NAME) VALUES ('Brisbane');
INSERT INTO REGION (NAME) VALUES ('South East');
INSERT INTO REGION (NAME) VALUES ('Far Northern');

--
-- SALUTATION
--
INSERT INTO SALUTATION (SALUTATION) VALUES ('-');
INSERT INTO SALUTATION (SALUTATION) VALUES ('Mr');
INSERT INTO SALUTATION (SALUTATION) VALUES ('Miss');
INSERT INTO SALUTATION (SALUTATION) VALUES ('Ms');
INSERT INTO SALUTATION (SALUTATION) VALUES ('Mrs');
INSERT INTO SALUTATION (SALUTATION) VALUES ('Dr');

--
-- SECURITY_GROUP
--
INSERT INTO SECURITY_GROUP (SECURITY_GROUP_ID, NAME, DESCRIPTION) VALUES
(1, 'Administrator', 'Administrator');
INSERT INTO SECURITY_GROUP (SECURITY_GROUP_ID, NAME, DESCRIPTION) VALUES
(2, 'AlarmTeamManager', 'Alarm Team Manager');
INSERT INTO SECURITY_GROUP (SECURITY_GROUP_ID, NAME, DESCRIPTION) VALUES
(3, 'AlarmTeam', 'Alarm Team');
INSERT INTO SECURITY_GROUP (SECURITY_GROUP_ID, NAME, DESCRIPTION) VALUES
(4, 'SupplierManager', 'Supplier Manager');
INSERT INTO SECURITY_GROUP (SECURITY_GROUP_ID, NAME, DESCRIPTION) VALUES
(5, 'SupplierTeam', 'Supplier Team');

--
-- SENT_METHOD
--
DELETE FROM SENT_METHOD;
INSERT INTO SENT_METHOD (SENT_METHOD_ID, NAME) VALUES (1, 'Australia Post');
INSERT INTO SENT_METHOD (SENT_METHOD_ID, NAME) VALUES (2, 'Pickup');

--
-- STATE
--
DELETE FROM STATE;
INSERT INTO STATE (STATE, DEFAULT_STATE) VALUES ('QLD', 'Y');
INSERT INTO STATE (STATE) VALUES ('NSW');
INSERT INTO STATE (STATE) VALUES ('VIC');
INSERT INTO STATE (STATE) VALUES ('ACT');
INSERT INTO STATE (STATE) VALUES ('TAS');
INSERT INTO STATE (STATE) VALUES ('SA');
INSERT INTO STATE (STATE) VALUES ('NT');
INSERT INTO STATE (STATE) VALUES ('WA');

--
-- STAKE_HOLDER_TYPE
--
INSERT INTO STAKE_HOLDER_TYPE (NAME) VALUES ('Community Safety');
INSERT INTO STAKE_HOLDER_TYPE (NAME) VALUES ('Regional Office');
INSERT INTO STAKE_HOLDER_TYPE (NAME) VALUES ('Area Director');

--
-- SUPPLIER_TYPE
--
INSERT INTO SUPPLIER_TYPE (NAME) VALUES ('Telco');
INSERT INTO SUPPLIER_TYPE (NAME) VALUES ('Fire Alarm Panel');
INSERT INTO SUPPLIER_TYPE (NAME) VALUES ('ASE');
INSERT INTO SUPPLIER_TYPE (NAME) VALUES ('ASE Installation');
INSERT INTO SUPPLIER_TYPE (NAME) VALUES ('Alarm Technician');

--
-- TEMPLATE_TYPE
--
INSERT INTO TEMPLATE_TYPE (NAME) VALUES ('Letter');
INSERT INTO TEMPLATE_TYPE (NAME) VALUES ('Email');
INSERT INTO TEMPLATE_TYPE (NAME) VALUES ('Fax');
INSERT INTO TEMPLATE_TYPE (NAME) VALUES ('Report (xslt-fo)');
INSERT INTO TEMPLATE_TYPE (NAME) VALUES ('Report (crystal)');
INSERT INTO TEMPLATE_TYPE (NAME) VALUES ('Export');
INSERT INTO TEMPLATE_TYPE (NAME) VALUES ('Pdf Form');

--
-- USER_TYPE
--
SET IDENTITY_INSERT USER_TYPE ON;
INSERT INTO USER_TYPE (USER_TYPE_ID, NAME) VALUES (0, 'System');
INSERT INTO USER_TYPE (USER_TYPE_ID, NAME) VALUES (1, 'Administrator');
INSERT INTO USER_TYPE (USER_TYPE_ID, NAME) VALUES (2, 'Staff Manager');
INSERT INTO USER_TYPE (USER_TYPE_ID, NAME) VALUES (3, 'Staff Team');
INSERT INTO USER_TYPE (USER_TYPE_ID, NAME) VALUES (4, 'Supplier Manager');
INSERT INTO USER_TYPE (USER_TYPE_ID, NAME) VALUES (5, 'Supplier Team');
SET IDENTITY_INSERT USER_TYPE OFF;

--
-- DELETE FROM SYSTEM_ACCESS; DELETE FROM SYSTEM_FUNCTION;
--
-- SYSTEM_FUNCTION
--
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1, '/', '/homepage', 'Main access');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(2, '/', '/getHomepage', 'Homepage access');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(3, '/', '/findFilter', 'Find Filter (like pattern)');

-- user
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(10, '/user', '/findUser', 'View all User');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(11, '/user', '/viewUser', 'View User details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(12, '/user', '/editUser', 'Edit User details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(13, '/user', '/changePassword', 'Change User password');
-- UI access
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (14, '/user', '/calendarStaff', 'Staff Management Calendar & Functions');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (15, '/user', '/calendarStaffSupervisor', 'Staff Management Calendar and Functions Supervisor', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (16, '/user', '/workflowRegister', 'Workflow/Action Item Register');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (17, '/user', '/', 'User (All)');

-- SETUP
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(100, '/setup', '/getSetup', 'Access setup data');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(101, '/setup', '/', 'Setup (All)');
-- ActionCode
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(110, '/setup', '/findActionCode', 'View all ActionCode');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(111, '/setup', '/viewActionCode', 'View ActionCode details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(112, '/setup', '/editActionCode', 'Edit ActionCode details');
-- ActionOutcome
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(120, '/setup', '/findActionOutcome', 'View all ActionOutcome');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(121, '/setup', '/viewActionOutcome', 'View ActionOutcome details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(122, '/setup', '/editActionOutcome', 'Edit ActionOutcome details');
-- SecurityGroup
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(130, '/setup', '/findSecurityGroup', 'View all SecurityGroup');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(131, '/setup', '/viewSecurityGroup', 'View SecurityGroup details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(132, '/setup', '/editSecurityGroup', 'Edit SecurityGroup details');
-- UserType
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(140, '/setup', '/findUserType', 'View all UserType');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(141, '/setup', '/viewUserType', 'View UserType details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(142, '/setup', '/editUserType', 'Edit UserType details');
-- DocType
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(150, '/setup', '/findDocType', 'View all DocType');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(151, '/setup', '/viewDocType', 'View DocType details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(152, '/setup', '/editDocType', 'Edit DocType details');
-- Template
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(160, '/setup', '/findTemplate', 'View all Template');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(161, '/setup', '/viewTemplate', 'View Template details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(162, '/setup', '/editTemplate', 'Edit Template details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(163, '/setup', '/helpTemplate', 'Template Help');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(164, '/setup', '/downloadTemplate', 'Download Template');
-- ActionWorkflow
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(170, '/setup', '/findActionWorkflow', 'View all ActionWorkflow');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(171, '/setup', '/viewActionWorkflow', 'View ActionWorkflow details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(172, '/setup', '/editActionWorkflow', 'Edit ActionWorkflow details');
-- Region
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(180, '/setup', '/findRegion', 'View all Region');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(181, '/setup', '/viewRegion', 'View Region details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(182, '/setup', '/editRegion', 'Edit Region details');
-- Area
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(190, '/setup', '/findArea', 'View all Area');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(191, '/setup', '/viewArea', 'View Area details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(192, '/setup', '/editArea', 'Edit Area details');
-- Station
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(200, '/setup', '/findStation', 'View all Station');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(201, '/setup', '/viewStation', 'View Station details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(202, '/setup', '/editStation', 'Edit Station details');
-- StakeholderType
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(210, '/setup', '/findStakeholderType', 'View all StakeholderType');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(211, '/setup', '/viewStakeholderType', 'View StakeholderType details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(212, '/setup', '/editStakeholderType', 'Edit StakeholderType details');
-- StakeholderData
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(220, '/setup', '/findStakeholder', 'View all Stakeholder');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(221, '/setup', '/viewStakeholder', 'View Stakeholder details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(222, '/setup', '/editStakeholder', 'Edit Stakeholder details');
-- SupplierType
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(230, '/setup', '/findSupplierType', 'View all SupplierType');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(231, '/setup', '/viewSupplierType', 'View SupplierType details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(232, '/setup', '/editSupplierType', 'Edit SupplierType details');
-- AseType
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(240, '/setup', '/findAseType', 'View all AseType');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(241, '/setup', '/viewAseType', 'View AseType details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(242, '/setup', '/editAseType', 'Edit AseType details');
-- AseConnType
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(250, '/setup', '/findAseConnType', 'View all AseConnType');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(251, '/setup', '/viewAseConnType', 'View AseConnType details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(252, '/setup', '/editAseConnType', 'Edit AseConnType details');
-- Salutation
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(260, '/setup', '/findSalutation', 'View all Salutation');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(261, '/setup', '/viewSalutation', 'View Salutation details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(262, '/setup', '/editSalutation', 'Edit Salutation details');
-- State
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(270, '/setup', '/findState', 'View all State');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(271, '/setup', '/viewState', 'View State details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(272, '/setup', '/editState', 'Edit State details');
-- FileStatus
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(280, '/setup', '/findFileStatus', 'View all FileStatus');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(281, '/setup', '/viewFileStatus', 'View FileStatus details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(282, '/setup', '/editFileStatus', 'Edit FileStatus details');
-- JobType
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(290, '/setup', '/findJobType', 'View all JobType');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(291, '/setup', '/viewJobType', 'View JobType details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(292, '/setup', '/editJobType', 'Edit JobType details');
-- WorkGroup
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(300, '/setup', '/findWorkGroup', 'View all WorkGroup');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(301, '/setup', '/viewWorkGroup', 'View WorkGroup details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(302, '/setup', '/editWorkGroup', 'Edit WorkGroup details');
-- DocChkList
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(310, '/setup', '/findDocChkList', 'View all DocChkList');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(311, '/setup', '/viewDocChkList', 'View DocChkList details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(312, '/setup', '/editDocChkList', 'Edit DocChkList details');
-- BuildingClassification
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(320, '/setup', '/findBuildingClassification', 'View all Building Classification');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(321, '/setup', '/viewBuildingClassification', 'View Building Classification details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(322, '/setup', '/editBuildingClassification', 'Edit Building Classification details');
-- SiteType
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (330, '/setup', '/findSiteType', 'View all Site Type');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (331, '/setup', '/viewSiteType', 'View Site Type details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (332, '/setup', '/editSiteType', 'Edit Site Type details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (333, '/setup', '/findLeaveType', 'View all Leave Type');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (334, '/setup', '/viewLeaveType', 'View Leave Type details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (335, '/setup', '/editLeaveType', 'Edit Leave Type details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (336, '/setup', '/mailType', 'Mail Type');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (337, '/setup', '/scheduledTask', 'Scheduled Task');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (338, '/setup', '/systemFunction', 'System Function');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (339, '/setup', '/downloadDocument', 'Download Document');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (340, '/setup', '/cache', 'Cache Management');

-- FILE
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1000, '/file', '/findFile', 'View all File');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1001, '/file', '/viewFile', 'View File details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1002, '/file', '/newFile', 'New File details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1003, '/file', '/editFile', 'Edit File details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1010, '/file', '/editDiary', 'New Diary');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1011, '/file', '/editCall', 'New Call');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1012, '/file', '/editLetter', 'New Letter');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1013, '/file', '/editEmail', 'New Email');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1014, '/file', '/editSMS', 'New SMS');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1015, '/file', '/editRFI', 'New RFI');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1016, '/file', '/editFileStatus', 'Change File Status');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1017, '/file', '/editJob', 'New Job');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1018, '/file', '/', 'File (All)');
-- file editable components
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1101, '/file', '/editBuilding', 'Edit File Building details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1102, '/file', '/editOwner', 'Edit File Owner details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1103, '/file', '/editFcaAse', 'Edit File FcaAse details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1104, '/file', '/editStationKey', 'Edit File Station/Keys details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1105, '/file', '/editAlarmPanel', 'Edit File AlarmPanel details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1106, '/file', '/editSapBilling', 'Edit File SapBilling details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1107, '/file', '/editFileDocChkList', 'Edit File FileDocChkList details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1108, '/file', '/editFileDoc', 'Edit File FileDoc details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1109, '/file', '/moveFileDoc', 'Move File FileDoc');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1110, '/file', '/addFileAction', 'Add File Action details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1111, '/file', '/viewFileAction', 'View File Action details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1112, '/file', '/editFileAction', 'Edit File Action details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1113, '/file', '/deleteFileAction', 'Delete File Action details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1114, '/file', '/findAseChange', 'Find File AseChange details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1115, '/file', '/viewAseChange', 'View File AseChange details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1116, '/file', '/calendarAseChange', 'Monthly AseChange Calendar');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1117, '/file', '/editAseChange', 'Edit File AseChange details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1118, '/file', '/downloadFileAction', 'Download File Action document');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(1119, '/file', '/downloadFileDoc', 'Download File FileDoc');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1120, '/file', '/viewOwner', 'View File Owner details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1121, '/file', '/viewFcaAse', 'View File FcaAse details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1122, '/file', '/viewStationKey', 'View File Station/Keys details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1123, '/file', '/viewAlarmPanel', 'View File AlarmPanel details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1124, '/file', '/viewBuilding', 'View File Building details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1125, '/file', '/viewCrmActionsToDo', 'View CRM Actions ToDo', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1126, '/file', '/viewCrmCompletedActions', 'View CRM Completed Actions', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1127, '/file', '/viewJobActionsToDo', 'View Job Actions ToDo', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1128, '/file', '/viewJobCompletedActions', 'View Job Completed Actions', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1129, '/file', '/viewFileDocChkList', 'View File FileDocChkList details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1130, '/file', '/viewFileDoc', 'View File FileDoc details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1131, '/file', '/viewStakeholder', 'View File Stakeholders', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1132, '/file', '/viewSapBilling', 'View File SapBilling details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1133, '/file', '/viewEmergencyContact', 'View File Emergency Contact details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1134, '/file', '/editEmergencyContact', 'Edit File Emergency Contact details');
-- 5.3.27. Multi-site Identification and Linkage (also see subPanel column)
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1135, '/file', '/viewMultiSite', 'View Multi-site Identification and Linkage details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1136, '/file', '/editMultiSite', 'Edit Multi-site Identification and Linkage details');
-- UI access
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1137, '/file', '/findCall', 'Call Taking Storage and Reporting');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1138, '/file', '/exportCall', 'Call Taking Storage and Reporting :: Export');
-- ASE Key
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1139, '/file', '/aseKey', 'ASE Keys');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, QUERY, NAME, DESCRIPTION)
 VALUES (1140, '/file', '/aseKey', 'parameter=export', 'ASE Keys :: Export');
-- MailRegister
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1141, '/file', '/mailRegister', 'Mail Register');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, QUERY, NAME, DESCRIPTION)
 VALUES (1142, '/file', '/mailRegister', 'parameter=export', 'Mail Register :: Export');
-- 5.3.4. Customer Enquiries
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1143, '/file', '/enquiry', 'Customer Enquiries');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, QUERY, DESCRIPTION)
 VALUES (1144, '/file', '/enquiry', 'parameter=export', 'Customer Enquiries :: Export');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1145, '/file', '/isolation', 'Isolation History', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1146, '/file', '/fileArchive', 'Archiving Register');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1147, '/file', '/uaaIncident', 'Unwanted Alarm Activation (UAA) Incident Details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1148, '/file', '/mailOut', 'Bulk Mail Out');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1149, '/file', '/uaaInvoice', 'Unwanted Alarm Activation (UAA) Invoice Details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1150, '/file', '/fileAudit', 'File Audit Details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1151, '/file', '/mailIn', 'Bulk Mail In');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1152, '/file', '/viewFcaDoc', 'View File FCA Documents', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1153, '/file', '/editFcaDoc', 'Edit File FCA Documents', 'Y');

-- FCA
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(2000, '/fca', '/findFca', 'View all Fca');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(2001, '/fca', '/viewFca', 'View Fca details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(2002, '/fca', '/editFca', 'Edit Fca details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(2003, '/fca', '/editFcaWarning', 'Edit Fca Warning details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(2004, '/fca', '/', 'FCA (All)');

-- SUPPLIER
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(3000, '/supplier', '/findSupplier', 'View all Supplier');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(3001, '/supplier', '/viewSupplier', 'View Supplier details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(3002, '/supplier', '/editSupplier', 'Edit Supplier details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(3003, '/supplier', '/', 'Supplier (All)');

-- TODO
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(4000, '/todo', '/findTodoJob', 'View all Todo Job Action');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(4001, '/todo', '/viewTodoJob', 'View Todo Job Action details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(4002, '/todo', '/editTodoJob', 'Edit Todo Job Action details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(4003, '/todo', '/', 'Todo (All)');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(4100, '/todo', '/findTodoFile', 'View all Todo File Action');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(4101, '/todo', '/viewTodoFile', 'View Todo File Action details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(4102, '/todo', '/editTodoFile', 'Edit Todo File Action details');

-- HOME
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(5000, '/home', '/findHome', 'View all Home');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(5001, '/home', '/viewHome', 'View Home details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(5002, '/home', '/editHome', 'Edit Home details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(5003, '/home', '/', 'Home (All)');

-- JOB
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6000, '/job', '/findJob', 'View all Job');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6001, '/job', '/viewJob', 'View Job');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6002, '/job', '/editJob', 'Edit Job (details view)');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6003, '/job', '/newJob', 'New Job details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6004, '/job', '/editJobDetails', 'Edit Job details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6005, '/job', '/editJobDoc', 'Edit Job Document');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6006, '/job', '/viewJobAction', 'View Job Action details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6007, '/job', '/addJobAction', 'Add Job Action details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6008, '/job', '/editJobAction', 'Edit Job Action details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6009, '/job', '/deleteJobAction', 'Delete Job Action details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6010, '/job', '/downloadJobAction', 'Download Job Action document');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6011, '/job', '/editDiary', 'New Diary');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6012, '/job', '/editCall', 'New Call');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6013, '/job', '/editLetter', 'New Letter');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6014, '/job', '/editEmail', 'New Email');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6015, '/job', '/editSMS', 'New SMS');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6016, '/job', '/editRFI', 'New RFI');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6017, '/job', '/closeJob', 'Close Job');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6018, '/job', '/', 'Job (All)');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6100, '/job', '/findJobRequest', 'View all JobRequest');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6101, '/job', '/viewJobRequest', 'View JobRequest details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6102, '/job', '/editJobRequest', 'Edit JobRequest details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6103, '/job', '/acceptJobRequest', 'Accept JobRequest details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6104, '/job', '/rejectJobRequest', 'Reject JobRequest details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6105, '/job', '/moveJobDoc', 'Move Job JobDoc');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(6200, '/job', '/calendarJobAction', 'Monthly Job Action Calendar');

-- REPORT
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(7000, '/report', '/findReport', 'View all Report');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(7001, '/report', '/generateReportDoc', 'Generate Report Document');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(7002, '/report', '/findReportDoc', 'Find User Report Document');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(7003, '/report', '/downloadReportDoc', 'Download User Report Document');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(7004, '/report', '/deleteReportDoc', 'Delete User Report Document');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(7005, '/report', '/helpReport', 'Report Help');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(7006, '/report', '/', 'Report (All)');

-- FINANCE
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (8000, '/finance', '/accountInfo', 'Enhanced SAP/Account Information');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (8001, '/finance', '/budget', 'Budgets');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (8002, '/finance', '/accountPayable', 'Accounts Payable');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (8003, '/finance', '/accrual', 'Accruals');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (8004, '/finance', '/invoiceGeneration', 'Annual Invoice Generation');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (8005, '/finance', '/accountHistory', 'Accounts History');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (8006, '/finance', '/externalInvoice', 'External Invoicing');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (8007, '/finance', '/debtInfo', 'Debt Information');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (8008, '/finance', '/creditControl', 'Credit Control');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
(8009, '/finance', '/', 'Finance (All)');

--
-- SYSTEM_ACCESS
--
-- Administrator=1
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 1);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 2);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 3);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 10);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 11);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 12);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 13);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 100);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 110);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 111);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 112);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 120);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 121);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 122);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 130);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 131);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 132);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 140);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 141);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 142);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 150);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 151);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 152);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 160);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 161);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 162);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 163);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 164);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 170);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 171);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 172);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 180);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 181);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 182);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 190);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 191);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 192);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 200);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 201);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 202);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 210);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 211);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 212);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 220);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 221);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 222);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 230);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 231);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 232);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 240);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 241);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 242);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 250);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 251);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 252);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 260);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 261);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 262);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 270);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 271);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 272);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 280);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 281);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 282);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 290);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 291);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 292);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 300);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 301);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 302);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 310);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 311);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 312);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 320);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 321);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 322);

INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 2000);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 2001);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 2002);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 2003);

INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 3000);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 3001);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 3002);

--
-- USERS
--
INSERT INTO CONTACT (SALUTATION,FIRST_NAME,SURNAME,EMAIL) VALUES
('Mr','Ad','Min','apollosoft.net.au@gmail.com');
INSERT INTO USERS (LOGIN, PASSWORD, PASSWORD_EXPIRE, CONTACT_ID, USER_TYPE_ID, SECURITY_GROUP_ID) VALUES
('admin', 'D41E98D1EAFA6D6011D3A70F1A5B92F0', getDate() + 600, @@IDENTITY, 1, 1);

INSERT INTO CONTACT (SALUTATION,FIRST_NAME,SURNAME,EMAIL) VALUES
('Mr','Valera','Shibaev','shibaev.valera@gmail.com');
INSERT INTO USERS (LOGIN, PASSWORD, PASSWORD_EXPIRE, CONTACT_ID, USER_TYPE_ID, SECURITY_GROUP_ID) VALUES
('shibaevv', 'BFE223F16F9735D2A258AD92DB677BFE', getDate() + 600, @@IDENTITY, 3, 2);
