-- login as [jms] default database [JMS]

USE [JMS];

CREATE TABLE ACTION_CODE (
    ACTION_CODE_ID numeric(11,0) identity NOT NULL,
    CODE varchar(64) NOT NULL,
    NOTATION varchar(255) NOT NULL,
    ACTION_TYPE_ID numeric(11,0) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    JOB_TYPE_ID numeric(11, 0) NULL,
    AREA_ID varchar(10),
    TEMPLATE_ID numeric(11,0),
    WORK_GROUP_ID numeric(11,0),
    BULK_MAIL char(1) NOT NULL DEFAULT 'N',
    DOCUMENT_TEMPLATE_ID numeric(11, 0) NULL,
    LOGICALLY_DELETED char(1) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ACTION_CODE ADD CONSTRAINT ACTION_CODE_PK PRIMARY KEY (ACTION_CODE_ID);

CREATE TABLE ACTION_OUTCOME (
    ACTION_OUTCOME_ID numeric(11,0) identity NOT NULL,
    NAME varchar(100) NOT NULL,
    FIXED char(1) NOT NULL DEFAULT 'N',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ACTION_OUTCOME ADD CONSTRAINT ACTION_OUTCOME_PK PRIMARY KEY (ACTION_OUTCOME_ID);

CREATE TABLE ACTION_TYPE (
    ACTION_TYPE_ID numeric(11,0) identity NOT NULL,
    NAME varchar(50) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ACTION_TYPE ADD CONSTRAINT ACTION_TYPE_PK PRIMARY KEY (ACTION_TYPE_ID);

CREATE TABLE ACTION_WORKFLOW (
    ACTION_WORKFLOW_ID numeric(11,0) identity NOT NULL,
    ACTION_CODE_ID numeric(11,0) NOT NULL,
    ACTION_OUTCOME_ID numeric(11,0) NOT NULL,
    NEXT_ACTION_CODE_ID numeric(11,0),
    NEXT_DUE_DAYS numeric(11,0) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);

ALTER TABLE ACTION_WORKFLOW ADD CONSTRAINT ACTION_WORKFLOW_PK PRIMARY KEY (ACTION_WORKFLOW_ID);

CREATE TABLE ADDRESS (
    ADDRESS_ID numeric(11,0) identity(10001,1) NOT NULL,
    ADDR_LINE_1 varchar(255) NOT NULL,
    ADDR_LINE_2 varchar(255),
    SUBURB varchar(255) NOT NULL,
    POSTCODE varchar(10),
    STATE varchar(3) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);

ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_PK PRIMARY KEY (ADDRESS_ID);

CREATE TABLE ALARM_PANEL (
    FILE_ID numeric(11,0) NOT NULL,
    SUPPLIER_ID numeric(11,0) NOT NULL,
    ALRM_SYST_TYPE varchar(255),
    ALRM_MANUF varchar(255),
    ALRM_MODEL varchar(255),
    PANEL_LOC varchar(255),
    SUB_PANEL_QTY numeric(11,0),
    DTHERM_QTY numeric(11,0),
    DSMOKE_QTY numeric(11,0),
    DCOMBUST_QTY numeric(11,0),
    DUV_QTY numeric(11,0),
    DINFRED_QTY numeric(11,0),
    DMULTIC_QTY numeric(11,0),
    DSPRINK_QTY numeric(11,0),
    DAIRSAMP_QTY numeric(11,0),
    DMANCALL_QTY numeric(11,0),
    DOTHER_QTY numeric(11,0),
    DOTHER_DEFINE varchar(255),
    SFS_DUAL_DETECT varchar(255),
    SFS_AIRCON varchar(255),
    SFS_ELEVATOR varchar(255),
    SFS_EVACCTRL varchar(255),
    SFS_FIREDOORS varchar(255),
    SFS_BOOSTER varchar(255),
    SFS_DRYPIPE varchar(255),
    SFS_OTHER varchar(255),
    MIMC_LOC varchar(255),
    MIMIC_LAYOUT varchar(255),
    AREA_CIRCDES varchar(255),
    MODS varchar(255),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ALARM_PANEL ADD CONSTRAINT ALARM_PANEL_PK PRIMARY KEY (FILE_ID, SUPPLIER_ID);

-- DROP TABLE ARCHIVE;
CREATE TABLE ARCHIVE (
    ARCHIVE_ID numeric(11, 0) IDENTITY NOT NULL,
    BOX_CODE varchar(32) NOT NULL,
    BOX_NAME varchar(50) NOT NULL,
    BOX_LOCATION varchar(255) NULL,
    BOX_DESCRIPTION varchar(512) NULL,
    DATE_FROM datetime NOT NULL,
    DATE_TO datetime NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);

-- sp_rename 'AREA.AREA_ID', 'AREA_CODE';
CREATE TABLE AREA (
    AREA_ID varchar(10) NOT NULL,
    NAME varchar(255) NOT NULL,
    REGION_ID numeric(11,0) NOT NULL,
    CONTACT_ID numeric(11,0) NOT NULL,
    ADDRESS_ID numeric(11,0) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE AREA ADD CONSTRAINT AREA_PK PRIMARY KEY (AREA_ID);

CREATE TABLE ASE_CHANGE (
    ASE_CHANGE_ID numeric(11,0) identity(10001,1) NOT NULL,
    ASE_FILE_ID numeric(11,0) NOT NULL,
    DATE_CHANGE datetime NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);

ALTER TABLE ASE_CHANGE ADD CONSTRAINT ASE_CHANGE_PK PRIMARY KEY (ASE_CHANGE_ID);

CREATE TABLE ASE_CHANGE_SUPPLIER (
    ASE_CHANGE_SUPPLIER_ID numeric(11,0) identity(10001,1) NOT NULL,
    ASE_CHANGE_ID numeric(11,0) NOT NULL,
    SUPPLIER_ID numeric(11,0) NOT NULL,
    ASE_CONN_TYPE_ID numeric(11,0),
    NOTATION varchar(255),
    DATE_COMPLETED datetime,
    LOGICALLY_DELETED char(1),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ASE_CHANGE_SUPPLIER ADD CONSTRAINT ASE_CHANGE_SUPPLIER_PK PRIMARY KEY (ASE_CHANGE_SUPPLIER_ID);

CREATE TABLE ASE_CONN (
    ASE_FILE_ID numeric(11,0) NOT NULL,
    ASE_CONN_TYPE_ID numeric(11,0),
    PRI_REF varchar(100),
    SEC_ASE_CONN_TYPE_ID numeric(11,0),
    SEC_REF varchar(100),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ASE_CONN ADD CONSTRAINT ASE_CONN_PK PRIMARY KEY (ASE_FILE_ID);

CREATE TABLE ASE_CONN_TYPE (
    ASE_CONN_TYPE_ID numeric(11,0) identity NOT NULL,
    NAME varchar(100) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ASE_CONN_TYPE ADD CONSTRAINT ASE_CONN_TYPE_PK PRIMARY KEY (ASE_CONN_TYPE_ID);

CREATE TABLE ASE_KEY (
    ASE_KEY_ID numeric(11, 0) NOT NULL,
    FILE_ID numeric(11, 0) NOT NULL,
    ASE_KEY_NO varchar(50) NULL,
    SUPPLIER_ID numeric(11,0) NULL,
    SENT_ADT_DATE datetime NULL,
    SENT_CUSTOMER_DATE datetime NULL,
    SENT_METHOD_ID numeric(11) NULL,
    SENT_REFERENCE_NO varchar(20) NULL,
    PAYMENT_METHOD_ID numeric(11) NULL,
    INVOICE_ID numeric(11) NULL,
    LICENSE_NO varchar(50) NULL,
    ASE_KEY_ORDER_ID numeric(11, 0),
    CONTACT_ID numeric(11, 0),
    STATUS_ID numeric(11, 0),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_PK PRIMARY KEY (ASE_KEY_ID);

CREATE TABLE ASE_KEY_INVOICE (
    INVOICE_ID numeric(11, 0) identity(10001,1) NOT NULL,
    INVOICE_NO varchar(20) NULL,
    INVOICE_DATE datetime NULL,
    INVOICE_AMOUNT decimal(19,2) NULL,
    AUTHORISED_BY numeric(11, 0) NULL,
    AUTHORISED_DATE datetime NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ASE_KEY_INVOICE ADD CONSTRAINT ASE_KEY_INVOICE_PK PRIMARY KEY (INVOICE_ID);

CREATE TABLE ASE_FILE (
    ASE_FILE_ID numeric(11,0) NOT NULL,
    FILE_ID numeric(11,0) NOT NULL,
    ASE_TYPE_ID numeric(11,0),
    ASE_SERIAL_NO varchar(50),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ASE_FILE ADD CONSTRAINT ASE_FILE_PK PRIMARY KEY (ASE_FILE_ID);

CREATE TABLE ASE_SUPPLIER (
    ASE_FILE_ID numeric(11,0) NOT NULL,
    SUPPLIER_ID numeric(11,0) NOT NULL
);
ALTER TABLE ASE_SUPPLIER ADD CONSTRAINT ASE_SUPPLIER_PK PRIMARY KEY (ASE_FILE_ID, SUPPLIER_ID);

CREATE TABLE ASE_TYPE (
    ASE_TYPE_ID numeric(11,0) identity NOT NULL,
    NAME varchar(100) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ASE_TYPE ADD CONSTRAINT ASE_TYPE_PK PRIMARY KEY (ASE_TYPE_ID);

CREATE TABLE AUDIT_STATUS (
    AUDIT_STATUS_ID INT NOT NULL,
    NAME varchar(100) NOT NULL,
    DESCRIPTION varchar(255) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0,
    CONSTRAINT AUDIT_STATUS_PK PRIMARY KEY CLUSTERED (AUDIT_STATUS_ID)
);

CREATE TABLE BRIGADE (
    BRIGADE_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    SAP_CUST_NO numeric(11, 0) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE BRIGADE ADD CONSTRAINT BRIGADE_PK PRIMARY KEY (BRIGADE_ID);

CREATE TABLE BUILDING (
    BUILDING_ID numeric(11,0) identity(10001,1) NOT NULL,
    NAME varchar(100) NOT NULL,
    DESCRIPTION varchar(255),
    USAGE varchar(255),
    KEY_REQUIRED char(1) NOT NULL DEFAULT 'N',
    FILE_ID numeric(11,0) NOT NULL,
    ADDRESS_ID numeric(11,0),
    ARCH_BY numeric(11,0),
    ARCH_DATE datetime,
    NEXT_BUILDING_ID numeric(11,0),
    LOT_PLAN_NUMBER varchar(30),
    ESCAD_BUILDING_ID numeric(11, 0),
    MASTERMIND_BUILDING_ID numeric(11, 0),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE BUILDING ADD CONSTRAINT BUILDING_PK PRIMARY KEY (BUILDING_ID);

CREATE TABLE BUILDING_ALT (
    BUILDING_ALT_ID numeric(11, 0) IDENTITY(10001,1) NOT NULL,
    NAME varchar(100) NOT NULL,
    FILE_ID numeric(11, 0) NOT NULL,
    ADDRESS_ID numeric(11, 0) NULL,
    TYPE char(1) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0,
    CONSTRAINT BUILDING_ALT_PK PRIMARY KEY CLUSTERED (BUILDING_ALT_ID)
);

CREATE TABLE BUILDING_CONTACT (
    BUILDING_CONTACT_ID numeric(11,0) identity NOT NULL,
    FILE_ID numeric(11,0) NOT NULL,
    CONTACT_ID numeric(11,0) NOT NULL,
    BUILDING_CONTACT_TYPE_ID numeric(11,0) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE BUILDING_CONTACT ADD CONSTRAINT BUILDING_CONTACT_PK PRIMARY KEY (BUILDING_CONTACT_ID);

CREATE TABLE BUILDING_CONTACT_TYPE (
    BUILDING_CONTACT_TYPE_ID numeric(11,0) identity NOT NULL,
    NAME varchar(100) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE BUILDING_CONTACT_TYPE ADD CONSTRAINT BUILDING_CONTACT_TYPE_PK PRIMARY KEY (BUILDING_CONTACT_TYPE_ID);

CREATE TABLE CONTACT (
    CONTACT_ID numeric(11,0) identity(10001,1) NOT NULL,
    SALUTATION varchar(50) NOT NULL,
    FIRST_NAME varchar(255) NOT NULL,
    SURNAME varchar(255) NOT NULL,
    DATE_OF_BIRTH datetime,
    PHONE varchar(50),
    MOBILE varchar(50),
    EMAIL varchar(50),
    FAX varchar(50),
    SKYPE varchar(50),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE CONTACT ADD CONSTRAINT CONTACT_PK PRIMARY KEY (CONTACT_ID);

-- =============================================================================
--    to keep track of db updates
--    version control    (XXX.01.01)
--        XXX - client org code (e.g. JMS)
--        01 - major version number
--        01 - minor version number
-- =============================================================================
CREATE TABLE DBVERSION (
  DBVERSION varchar(32) NOT NULL,
  PREV_DBVERSION varchar(32),
  CREATED_DATE datetime NOT NULL DEFAULT getDate(),
  PRIMARY KEY  (DBVERSION)
);

CREATE TABLE DOC_CHK_LIST (
    DOC_CHK_LIST_ID numeric(11,0) identity(10001,1) NOT NULL,
    TEMPLATE_ID numeric(11,0) NOT NULL,
    ACTIVE char(1) NOT NULL,
    START_DATE datetime,
    END_DATE datetime,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE DOC_CHK_LIST ADD CONSTRAINT DOC_CHK_LIST_PK PRIMARY KEY (DOC_CHK_LIST_ID);

CREATE TABLE DOC_TYPE (
    DOC_TYPE_ID numeric(11,0) identity NOT NULL,
    NAME varchar(50) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE DOC_TYPE ADD CONSTRAINT DOC_TYPE_PK PRIMARY KEY (DOC_TYPE_ID);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID numeric(11,0) identity(10001,1) NOT NULL,
    NAME varchar(100) NOT NULL,
    DESCRIPTION varchar(255),
    CONTENT image NOT NULL,
    CONTENT_TYPE varchar(60),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE DOCUMENT ADD CONSTRAINT DOCUMENT_PK PRIMARY KEY (DOCUMENT_ID);

CREATE TABLE FCA (
    FCA_NO varchar(8) NOT NULL,
    FILE_ID numeric(11,0),
    REGION_ID numeric(11,0),
    AREA_ID varchar(10),
    STATION_CODE varchar(10),
    SUB_PANEL char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE FCA ADD CONSTRAINT FCA_PK PRIMARY KEY (FCA_NO);

CREATE TABLE FILE_ACTION (
    FILE_ACTION_ID numeric(11,0) identity(10001,1) NOT NULL,
    FILE_ID numeric(11,0) NOT NULL,
    DUE_DATE datetime NOT NULL,
    ACTION_CODE_ID numeric(11,0) NOT NULL,
    NOTATION varchar(4098) NOT NULL,
    DESTINATION varchar(250),
    SUBJECT varchar(250),
    ACTION_OUTCOME_ID numeric(11,0),
    DOCUMENT_ID numeric(11,0),
    ATTACHMENT_ID numeric(11, 0) NULL,
    CONTACT_ID numeric(11,0) NULL,
    LINK_ID numeric(11,0) NULL,
    RESPONSIBLE_USER_ID numeric(11, 0) NULL,
    PARENT_ACTION_ID numeric(11, 0) NULL,
    PARENT_JOB_ACTION_ID numeric(11, 0) NULL,
    COMPLETED_BY numeric(11,0),
    COMPLETED_DATE datetime,
    LOGICALLY_DELETED char(1),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_PK PRIMARY KEY (FILE_ACTION_ID);

-- DROP TABLE FILE_ARCHIVE;
CREATE TABLE FILE_ARCHIVE (
    FILE_ID numeric(11, 0) NOT NULL,
    ARCHIVE_ID numeric(11, 0) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);

CREATE TABLE FILE_AUDIT (
    FILE_ID numeric(11, 0) NOT NULL,
    NAME varchar(100) NULL,
    DESCRIPTION varchar(255) NULL,
    CONTENT image NOT NULL,
    DOCUMENT_ID numeric(11,0) NULL,
    AUDIT_STATUS_ID INT NOT NULL DEFAULT 1,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0,
    CONSTRAINT FILE_AUDIT_PK PRIMARY KEY CLUSTERED (FILE_ID)
);

CREATE TABLE FILE_AUDIT_AUD (
    FILE_ID numeric(11, 0) NOT NULL,
    NAME varchar(100) NULL,
    DESCRIPTION varchar(255) NULL,
    CONTENT image NULL,
    AUDIT_STATUS_ID int NULL,
    CREATED_BY numeric(11, 0) NULL,
    CREATED_DATE datetime NULL,
    UPDATED_BY numeric(11, 0) NULL,
    UPDATED_DATE datetime NULL,
    LOCK_VERSION numeric(11, 0) NULL,
    DOCUMENT_ID numeric(11, 0) NULL,
    REV_ID numeric(11,0) NOT NULL,
    REV_TYPE tinyint NOT NULL,
    CONSTRAINT FILE_AUDIT_AUD_PK PRIMARY KEY CLUSTERED (FILE_ID, REV_ID)
);

CREATE TABLE FILE_DOC (
    FILE_DOC_ID numeric(11,0) identity(10001,1) NOT NULL,
    FILE_ID numeric(11,0) NOT NULL,
    DOC_TYPE_ID numeric(11,0) NOT NULL,
    NAME varchar(100),
    DESCRIPTION varchar(255),
    LOCATION varchar(255),
    DOCUMENT_ID numeric(11,0),
    UPLOAD_DATE datetime,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE FILE_DOC ADD CONSTRAINT FILE_DOC_PK PRIMARY KEY (FILE_DOC_ID);

CREATE TABLE FILE_DOC_CHK_LIST (
    FILE_ID numeric(11,0) NOT NULL,
    DOC_CHK_LIST_ID numeric(11,0) NOT NULL,
    DOC_ON_FILE char(1) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE FILE_DOC_CHK_LIST ADD CONSTRAINT FILE_DOC_CHK_LIST_PK PRIMARY KEY (FILE_ID, DOC_CHK_LIST_ID);

CREATE TABLE FILE_STATUS (
    FILE_STATUS_ID numeric(11,0) NOT NULL,
    NAME varchar(50) NOT NULL
);
ALTER TABLE FILE_STATUS ADD CONSTRAINT FILE_STATUS_PK PRIMARY KEY (FILE_STATUS_ID);

CREATE TABLE FILE_TYPE (
    FILE_TYPE_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE FILE_TYPE ADD CONSTRAINT FILE_TYPE_PK PRIMARY KEY (FILE_TYPE_ID);

CREATE TABLE FILES (
    FILE_ID numeric(11,0) identity(10001,1) NOT NULL,
    FILE_TYPE_ID numeric(11,0) NULL,
    FILE_STATUS_ID numeric(11,0) NOT NULL,
    NO_MAIL_OUT char(1) NOT NULL DEFAULT 'N',
    MAIL_METHOD_ID numeric(11, 0),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE FILES ADD CONSTRAINT FILES_PK PRIMARY KEY (FILE_ID);

CREATE TABLE INVOICE (
    INVOICE_ID numeric(11, 0) IDENTITY(10001,1) NOT NULL,
    INVOICE_TYPE_ID numeric(11, 0) NOT NULL,
    INVOICE_AREA_ID numeric(11, 0) NOT NULL,
    FISCAL_YEAR numeric(4, 0) NOT NULL,
    REGION_ID numeric(11, 0) NULL,
    BRIGADE_ID numeric(11, 0) NULL,
    RECEIPT_BATCH varchar(8) NULL,
    DATE_RECEIVED datetime NOT NULL,
    DATE_ACTIONED datetime NULL,
    JOB_REFERENCE varchar(20) NULL,
    INCIDENT_DATE datetime NULL,
    SAP_CUST_NO numeric(11, 0) NULL,
    SAP_CUST_CREATE char(1) NOT NULL DEFAULT 'N',
    SAP_CUST_CHANGE char(1) NOT NULL DEFAULT 'N',
    SAP_CUST_UNBLOCK char(1) NOT NULL DEFAULT 'N',
    INVOICE_BATCH_ID numeric(11, 0) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_PK PRIMARY KEY (INVOICE_ID);

CREATE TABLE INVOICE_AREA (
    INVOICE_AREA_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    DESCRIPTION varchar(250) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE INVOICE_AREA ADD CONSTRAINT INVOICE_AREA_PK PRIMARY KEY (INVOICE_AREA_ID);

CREATE TABLE INVOICE_BATCH (
    INVOICE_BATCH_ID numeric(11, 0) NOT NULL,
    INVOICE_TYPE_ID numeric(11, 0) NOT NULL,
    INVOICE_AREA_ID numeric(11, 0) NOT NULL,
    FISCAL_YEAR numeric(4, 0) NOT NULL,
    MONTH numeric(2, 0) NOT NULL,
    DAY numeric(2, 0) NOT NULL,
    SEQUENCE numeric(9, 0) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE INVOICE_BATCH ADD CONSTRAINT INVOICE_BATCH_PK PRIMARY KEY (INVOICE_BATCH_ID);

CREATE TABLE INVOICE_TYPE (
    INVOICE_TYPE_ID numeric(11, 0) NOT NULL,
    INVOICE_AREA_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE INVOICE_TYPE ADD CONSTRAINT INVOICE_TYPE_PK PRIMARY KEY (INVOICE_TYPE_ID);

CREATE TABLE ISOLATION_HISTORY (
    ISOLATION_HISTORY_ID numeric(11, 0) IDENTITY NOT NULL,
    FCA_NO varchar(8) NOT NULL,
    CS_NUMBER varchar(32) NULL,
    ISOLATION_DATE datetime NOT NULL,
    DE_ISOLATION_DATE datetime NOT NULL,
    INPUT numeric(3,0) NOT NULL,
    DETAILS varchar(512) NULL,
    KEY_DETAILS varchar(512) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);

CREATE TABLE JOB_ACTION (
    JOB_ACTION_ID numeric(11,0) identity(10001,1) NOT NULL,
    JOB_ID numeric(11,0) NOT NULL,
    DUE_DATE datetime NOT NULL,
    ACTION_CODE_ID numeric(11,0) NOT NULL,
    NOTATION varchar(4098) NOT NULL,
    DESTINATION varchar(250),
    SUBJECT varchar(250),
    ACTION_OUTCOME_ID numeric(11,0),
    DOCUMENT_ID numeric(11,0),
    CONTACT_ID numeric(11,0) NULL,
    LINK_ID numeric(11,0) NULL,
    RESPONSIBLE_USER_ID numeric(11, 0) NULL,
    PARENT_ACTION_ID numeric(11, 0) NULL,
    PARENT_FILE_ACTION_ID numeric(11, 0) NULL,
    COMPLETED_BY numeric(11,0),
    COMPLETED_DATE datetime,
    LOGICALLY_DELETED char(1),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_PK PRIMARY KEY (JOB_ACTION_ID);

CREATE TABLE JOB_DOC (
    JOB_DOC_ID numeric(11,0) identity(10001,1) NOT NULL,
    JOB_ID numeric(11,0) NOT NULL,
    DOC_TYPE_ID numeric(11,0) NOT NULL,
    NAME varchar(100),
    DESCRIPTION varchar(255),
    LOCATION varchar(255),
    DOCUMENT_ID numeric(11,0),
    ATTACHMENT_ID numeric(11, 0) NULL,
    UPLOAD_DATE datetime,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE JOB_DOC ADD CONSTRAINT JOB_DOC_PK PRIMARY KEY (JOB_DOC_ID);

CREATE TABLE JOB_REQUEST (
    JOB_REQUEST_ID numeric(11,0) identity(10001,1) NOT NULL,
    DESCRIPTION varchar(255) NOT NULL,
    JOB_TYPE_ID numeric(11,0) NOT NULL,
    REQUESTED_BY numeric(11,0) NOT NULL,
    REQUESTED_DATE datetime NOT NULL,
    REQUESTED_EMAIL varchar(255) NOT NULL,
    LINK varchar(255) NOT NULL,
    FCA_NO varchar(8) NOT NULL,
    ACCEPTED char(1),
    REJECT_REASON varchar(255),
    ACCEPTED_BY numeric(11,0),
    ACCEPTED_DATE datetime,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE JOB_REQUEST ADD CONSTRAINT JOB_REQUEST_PK PRIMARY KEY (JOB_REQUEST_ID);

CREATE TABLE JOB_TYPE (
    JOB_TYPE_ID numeric(11,0) identity NOT NULL,
    NAME varchar(100) NOT NULL,
    SECURITY_GROUP_ID numeric(11,0),
    CLOSE_JOB_SECURITY_GROUP_ID numeric(11,0),
    ACTION_CODE_ID numeric(11,0),
    WORK_GROUP_ID numeric(11,0),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE JOB_TYPE ADD CONSTRAINT JOB_TYPE_PK PRIMARY KEY (JOB_TYPE_ID);

CREATE TABLE JOBS (
    JOB_ID numeric(11,0) identity(10001,1) NOT NULL,
    DESCRIPTION varchar(255) NOT NULL,
    JOB_TYPE_ID numeric(11,0) NOT NULL,
    FILE_ID numeric(11,0) NOT NULL,
    JOB_REQUEST_ID numeric(11,0),
    REQUESTED_EMAIL varchar(255),
    LINK varchar(255),
    FCA_NO varchar(8),
    STATUS char(1) NOT NULL DEFAULT 'Y',
    COMPLETED_BY numeric(11,0),
    COMPLETED_DATE datetime,
    CLOSE_REASON varchar(255),
    RESPONSIBLE_USER_ID numeric(11, 0) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE JOBS ADD CONSTRAINT JOBS_PK PRIMARY KEY (JOB_ID);

CREATE TABLE HIBERNATE_SEQUENCES (
  SEQUENCE_NAME varchar(32) NOT NULL,
  NEXT_VAL numeric(11, 0) NOT NULL
);
ALTER TABLE HIBERNATE_SEQUENCES ADD CONSTRAINT HIBERNATE_SEQUENCES_PK PRIMARY KEY (SEQUENCE_NAME);

CREATE TABLE KEY_RECEIPT (
    KEY_RECEIPT_ID numeric(11,0) identity(10001,1) NOT NULL,
    FILE_ID numeric(11,0) NOT NULL,
    KEY_RECEIPT_NO varchar(50),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE KEY_RECEIPT ADD CONSTRAINT KEY_RECEIPT_PK PRIMARY KEY (KEY_RECEIPT_ID);

CREATE TABLE KEY_REG (
    KEY_REG_ID numeric(11,0) identity(10001,1) NOT NULL,
    FILE_ID numeric(11,0) NOT NULL,
    KEY_NO varchar(10),
    OWNER_KEY_ID varchar(20),
    LOCK_TYPE varchar(100),
    LOCK_LOCATION varchar(150),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE KEY_REG ADD CONSTRAINT KEY_REG_PK PRIMARY KEY (KEY_REG_ID);

CREATE TABLE LEAVE_STATUS (
    LEAVE_STATUS_ID numeric(11, 0) IDENTITY NOT NULL,
    NAME varchar(50) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE LEAVE_STATUS ADD CONSTRAINT LEAVE_STATUS_PK PRIMARY KEY (LEAVE_STATUS_ID);

CREATE TABLE LEAVE_TYPE (
    LEAVE_TYPE_ID numeric(11, 0) IDENTITY NOT NULL,
    NAME varchar(50) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE LEAVE_TYPE ADD CONSTRAINT LEAVE_TYPE_PK PRIMARY KEY (LEAVE_TYPE_ID);

CREATE TABLE MAIL_BATCH_STATUS (
    MAIL_BATCH_STATUS_ID INT NOT NULL,
    NAME varchar(100) NOT NULL,
    DESCRIPTION varchar(255) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0,
    CONSTRAINT MAIL_BATCH_STATUS_PK PRIMARY KEY CLUSTERED (MAIL_BATCH_STATUS_ID)
);

CREATE TABLE MAIL_BATCH (
    MAIL_BATCH_ID numeric(11, 0) IDENTITY(10001,1) NOT NULL,
    NAME varchar(50) NOT NULL,
    DESCRIPTION varchar(250) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0,
    CONSTRAINT MAIL_BATCH_PK PRIMARY KEY CLUSTERED (MAIL_BATCH_ID)
);
ALTER TABLE MAIL_BATCH ADD CONSTRAINT MAIL_BATCH_UK1 UNIQUE (NAME);

CREATE TABLE MAIL_BATCH_FILE (
    MAIL_BATCH_FILE_ID numeric(11, 0) IDENTITY NOT NULL,
    MAIL_BATCH_ID numeric(11, 0) NOT NULL,
    FILE_ID numeric(11, 0) NOT NULL,
    FILE_ACTION_ID numeric(11,0) NULL,
    JOB_ACTION_ID numeric(11,0) NULL,
    STATUS_ID INT NULL,
    SENT_DATE datetime NULL,
    RECEIVED_DATE datetime NULL,
    REJECTED_DATE datetime NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0,
    CONSTRAINT MAIL_BATCH_FILE_PK PRIMARY KEY CLUSTERED (MAIL_BATCH_FILE_ID)
);

CREATE TABLE MAIL_METHOD (
    MAIL_METHOD_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0,
    CONSTRAINT MAIL_METHOD_PK PRIMARY KEY CLUSTERED (MAIL_METHOD_ID)
);

CREATE TABLE MAIL_REGISTER (
    MAIL_REGISTER_ID numeric(11, 0) IDENTITY NOT NULL,
    FILE_ID numeric(11, 0) NOT NULL,
    MAIL_TYPE_ID numeric(11) NULL,
    MAIL_REGISTER_DATE datetime NOT NULL,
    MAIL_REGISTER_NO varchar(50) NULL,
    MAIL_REGISTER_DETAILS varchar(512) NULL,
    MAIL_IN char(1) NOT NULL DEFAULT 'Y',
    RTS char(1) NOT NULL DEFAULT 'N',
    CONTACT_ID numeric(11,0) NULL,
    ADDRESS_ID numeric(11,0) NULL,
    WORK_GROUP_ID numeric(11,0) NULL,
    USER_ID numeric(11,0) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);

CREATE TABLE MAIL_TYPE (
    MAIL_TYPE_ID numeric(11, 0) IDENTITY NOT NULL,
    NAME varchar(50) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE MAIL_TYPE ADD CONSTRAINT MAIL_TYPE_PK PRIMARY KEY (MAIL_TYPE_ID);

CREATE TABLE OWNER (
    OWNER_ID numeric(11,0) identity(10001,1) NOT NULL,
    OWNER_TYPE_ID numeric(11,0) NOT NULL,
    LEGAL_NAME varchar(255) NOT NULL,
    FILE_ID numeric(11,0) NOT NULL,
    ABN varchar(20) NULL,
    REFERENCE varchar(20) NULL,
    CONTACT_ID numeric(11,0) NOT NULL,
    DEFAULT_CONTACT char(1) NOT NULL DEFAULT 'N',
    ADDRESS_ID numeric(11,0) NOT NULL,
    NEXT_OWNER_ID numeric(11,0) NULL,
    ARCH_DATE datetime NULL,
    ARCH_BY numeric(11,0) NULL,
    OWNER_OCCUPIED char(1) NOT NULL DEFAULT 'N',
    MANAGEMENT varchar(50) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE OWNER ADD CONSTRAINT OWNER_PK PRIMARY KEY (OWNER_ID);

CREATE TABLE OWNER_TYPE (
    OWNER_TYPE_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE OWNER_TYPE ADD CONSTRAINT OWNER_TYPE_PK PRIMARY KEY (OWNER_TYPE_ID);

CREATE TABLE PAYMENT_METHOD (
    PAYMENT_METHOD_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE PAYMENT_METHOD ADD CONSTRAINT PAYMENT_METHOD_PK PRIMARY KEY (PAYMENT_METHOD_ID);

CREATE TABLE REGION (
    REGION_ID numeric(11,0) identity NOT NULL,
    NAME varchar(100) NOT NULL,
    CONTACT_ID numeric(11,0),
    ADDRESS_ID numeric(11,0),
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CODE varchar(3) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE REGION ADD CONSTRAINT REGION_PK PRIMARY KEY (REGION_ID);

CREATE TABLE REPORT_DOC (
    REPORT_DOC_ID numeric(11,0) identity(10001,1) NOT NULL,
    DOC_TYPE_ID numeric(11,0) NOT NULL,
    TEMPLATE_ID numeric(11,0),
    NAME varchar(100),
    DESCRIPTION varchar(255),
    LOCATION varchar(255),
    DOCUMENT_ID numeric(11,0),
    UPLOAD_DATE datetime,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE REPORT_DOC ADD CONSTRAINT REPORT_DOC_PK PRIMARY KEY (REPORT_DOC_ID);

CREATE TABLE RFI (
    RFI_ID numeric(11,0) identity(10001,1) NOT NULL,
    DESCRIPTION varchar(255) NOT NULL,
    FILE_ID numeric(11,0) NOT NULL,
    FILE_ACTION_ID numeric(11,0) NOT NULL,
    SAP_INV_NO varchar(50),
    SAP_INV_DATE datetime,
    SAP_INV_COMP_BY numeric(11,0),
    RFI_DEL_BY numeric(11,0),
    RFI_DEL_DATE datetime,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE RFI ADD CONSTRAINT RFI_PK PRIMARY KEY (RFI_ID);

CREATE TABLE REVINFO (
    REV_ID        numeric(11,0) IDENTITY NOT NULL,
    REV_TSTMP     bigint                 NOT NULL,
    CONSTRAINT REVINFO_PK PRIMARY KEY CLUSTERED (REV_ID)
);

CREATE TABLE SALUTATION (
    SALUTATION varchar(50) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);

ALTER TABLE SALUTATION ADD CONSTRAINT SALUTATION_PK PRIMARY KEY (SALUTATION);

CREATE TABLE SAP_HEADER (
    FILE_ID numeric(11,0) NOT NULL,
    SAP_CUST_NO numeric(11,0) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE SAP_HEADER ADD CONSTRAINT SAP_HEADER_PK PRIMARY KEY (FILE_ID);

CREATE TABLE SCHEDULED_TASK_HISTORY (
    SCHEDULED_TASK_HISTORY_ID numeric(11, 0) IDENTITY NOT NULL,
    SCHEDULED_TASK_ID numeric(11, 0) NOT NULL,
    TASK_NAME varchar(50) NULL,
    REQUEST varchar(512) NULL,
    RESPONSE varchar(512) NULL,
    STATUS char(1) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE SCHEDULED_TASK_HISTORY ADD CONSTRAINT SCHEDULED_TASK_HISTORY_PK PRIMARY KEY (SCHEDULED_TASK_HISTORY_ID);

CREATE TABLE SCHEDULED_TASK_HISTORY_ITEM (
    SCHEDULED_TASK_HISTORY_ITEM_ID numeric(11, 0) IDENTITY NOT NULL,
    SCHEDULED_TASK_HISTORY_ID numeric(11, 0) NOT NULL,
    ITEM_ID varchar(50) NOT NULL,
    SENT_DATE datetime NULL,
    RECEIVED_DATE datetime NULL,
    ITEM_FROM varchar(250) NULL,
    CONSTRAINT SCHEDULED_TASK_HISTORY_ITEM_PK PRIMARY KEY CLUSTERED (SCHEDULED_TASK_HISTORY_ITEM_ID)
);

CREATE TABLE SECURITY_GROUP (
    SECURITY_GROUP_ID numeric(11,0) NOT NULL,
    NAME varchar(50) NOT NULL,
    DESCRIPTION varchar(255) NOT NULL,
    CREATED_BY numeric(11),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime DEFAULT getDate(),
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE SECURITY_GROUP ADD CONSTRAINT SECURITY_GROUP_PK PRIMARY KEY (SECURITY_GROUP_ID);

CREATE TABLE SENT_METHOD (
    SENT_METHOD_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE SENT_METHOD ADD CONSTRAINT SENT_METHOD_PK PRIMARY KEY (SENT_METHOD_ID);

CREATE TABLE STAKE_HOLDER (
    STAKE_HOLDER_ID numeric(11,0) identity(10001,1) NOT NULL,
    STAKE_HOLDER_TYPE_ID numeric(11,0) NOT NULL,
    REGION_ID numeric(11,0) NOT NULL,
    CONTACT_ID numeric(11,0) NOT NULL,
    ADDRESS_ID numeric(11,0) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE STAKE_HOLDER ADD CONSTRAINT STAKE_HOLDER_PK PRIMARY KEY (STAKE_HOLDER_ID);

CREATE TABLE STAKE_HOLDER_TYPE (
    STAKE_HOLDER_TYPE_ID numeric(11,0) identity NOT NULL,
    NAME varchar(50) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE STAKE_HOLDER_TYPE ADD CONSTRAINT STAKE_HOLDER_TYPE_PK PRIMARY KEY (STAKE_HOLDER_TYPE_ID);

CREATE TABLE STATE (
    STATE varchar(3) NOT NULL,
    DEFAULT_STATE char(1)
);
ALTER TABLE STATE ADD CONSTRAINT STATE_PK PRIMARY KEY (STATE);

CREATE TABLE STATION (
    STATION_CODE varchar(10) NOT NULL,
    NAME varchar(255) NOT NULL,
    AREA_ID varchar(10) NOT NULL,
    CONTACT_ID numeric(11,0) NOT NULL,
    ADDRESS_ID numeric(11,0) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE STATION ADD CONSTRAINT STATION_PK PRIMARY KEY (STATION_CODE);

CREATE TABLE STAFF_LEAVE (
    STAFF_LEAVE_ID numeric(11, 0) IDENTITY NOT NULL,
    USER_ID numeric(11, 0) NOT NULL,
    LEAVE_GROUP_ID numeric(11, 0) NOT NULL,
    LEAVE_TYPE_ID numeric(11, 0) NOT NULL,
    LEAVE_DATE date NOT NULL,
    DESCRIPTION varchar(255) NULL,
    STATUS_ID numeric(11, 0) NULL,
    STATUS_BY numeric(11,0),
    STATUS_DATE datetime,
    LEAVE_TAKEN numeric(3, 2) NOT NULL DEFAULT 1.00,
    FORM_RECEIVED char(1) NOT NULL DEFAULT 'N',
    FORM_SENT_HR_DATE datetime NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE STAFF_LEAVE ADD CONSTRAINT STAFF_LEAVE_PK PRIMARY KEY (STAFF_LEAVE_ID);

CREATE TABLE SUB_PANEL (
    ASE_FILE_ID numeric(11,0) NOT NULL,
    SUB_PANEL_ORDER_ID numeric(11,0) NOT NULL,
    BUILDING_NAME varchar(250) NOT NULL,
    ADDRESS_ID numeric(11,0) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE SUB_PANEL ADD CONSTRAINT SUB_PANEL_PK PRIMARY KEY (SUB_PANEL_ORDER_ID, ASE_FILE_ID);

CREATE TABLE SUPPLIER (
    SUPPLIER_ID numeric(11,0) identity(10001,1) NOT NULL,
    SUPPLIER_TYPE_ID numeric(11,0) NOT NULL,
    NAME varchar(255) NOT NULL,
    LEGAL_NAME varchar(255) NOT NULL,
    ABN varchar(11),
    REGION_ID numeric(11,0),
    CONTACT_ID numeric(11,0),
    ADDRESS_ID numeric(11,0),
    POST_ADDRESS_ID numeric(11,0),
    SERVICE_DESCRIPTION varchar(255),
    MASTER_SUPPLIER_ID numeric(11,0),
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_PK PRIMARY KEY (SUPPLIER_ID);

CREATE TABLE SUPPLIER_TYPE (
    SUPPLIER_TYPE_ID numeric(11,0) identity NOT NULL,
    NAME varchar(100) NOT NULL,
    CHARGEABLE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE SUPPLIER_TYPE ADD CONSTRAINT SUPPLIER_TYPE_PK PRIMARY KEY (SUPPLIER_TYPE_ID);

CREATE TABLE SUPPLIER_TYPE_MATCH (
    SUPPLIER_ID numeric(11,0) NOT NULL,
    SUPPLIER_TYPE_ID numeric(11,0) NOT NULL
);
ALTER TABLE SUPPLIER_TYPE_MATCH ADD CONSTRAINT SUPPLIER_TYPE_MATCH_PK PRIMARY KEY (SUPPLIER_ID, SUPPLIER_TYPE_ID);

CREATE TABLE SYSTEM_ACCESS (
    SECURITY_GROUP_ID numeric(11,0) NOT NULL,
    SYSTEM_FUNCTION_ID numeric(11,0) NOT NULL
);
ALTER TABLE SYSTEM_ACCESS ADD CONSTRAINT SYSTEM_ACCESS_PK PRIMARY KEY (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID);

CREATE TABLE SYSTEM_FUNCTION (
    SYSTEM_FUNCTION_ID numeric(11,0) NOT NULL,
    NAME varchar(100) NOT NULL,
    QUERY varchar(255),
    MODULE varchar(50) NOT NULL,
    DESCRIPTION varchar(255) NOT NULL,
    LOGICAL CHAR(1) NULL
);
-- ALTER TABLE SYSTEM_FUNCTION ADD QUERY varchar(255);
ALTER TABLE SYSTEM_FUNCTION ADD CONSTRAINT SYSTEM_FUNCTION_PK PRIMARY KEY (SYSTEM_FUNCTION_ID);

CREATE TABLE TEMPLATE (
    TEMPLATE_ID numeric(11,0) identity(10001,1) NOT NULL,
    TEMPLATE_TYPE_ID numeric(11,0) NOT NULL,
    CODE varchar(50),
    NAME varchar(100) NOT NULL,
    DESCRIPTION varchar(255),
    LOCATION varchar(255),
    -- BODY varchar(255),
    CONTENT image,
    CONTENT_TYPE varchar(60),
    UPLOAD_DATE datetime,
    SQL_QUERY varchar(1024),
    CONFIG_DOCUMENT_ID numeric(11, 0) NULL,
    LOGICALLY_DELETED char(1) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE TEMPLATE ADD CONSTRAINT TEMPLATE_PK PRIMARY KEY (TEMPLATE_ID);

CREATE TABLE TEMPLATE_TYPE (
    TEMPLATE_TYPE_ID numeric(11,0) identity NOT NULL,
    NAME varchar(100) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE TEMPLATE_TYPE ADD CONSTRAINT TEMPLATE_TYPE_PK PRIMARY KEY (TEMPLATE_TYPE_ID);

CREATE TABLE USER_TYPE (
    USER_TYPE_ID numeric(11,0) identity NOT NULL,
    NAME varchar(100) NOT NULL
);
ALTER TABLE USER_TYPE ADD CONSTRAINT USER_TYPE_PK PRIMARY KEY (USER_TYPE_ID);

CREATE TABLE USERS (
    USER_ID numeric(11,0) identity(10001,1) NOT NULL,
    LOGIN varchar(100) NOT NULL,
    PASSWORD varchar(100) NOT NULL,
    PASSWORD_EXPIRE datetime NULL,
    CONTACT_ID numeric(11,0) NOT NULL,
    USER_TYPE_ID numeric(11,0) NOT NULL,
    SECURITY_GROUP_ID numeric(11,0) NOT NULL,
    SUPPLIER_ID numeric(11,0),
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY (USER_ID);

CREATE TABLE USERS_WORKGROUP (
    USER_ID numeric(11, 0) NOT NULL,
    WORK_GROUP_ID numeric(11, 0) NOT NULL
);
ALTER TABLE USERS_WORKGROUP ADD CONSTRAINT USERS_WORKGROUP_PK PRIMARY KEY (USER_ID, WORK_GROUP_ID);

CREATE TABLE WORK_GROUP (
    WORK_GROUP_ID numeric(11,0) identity NOT NULL,
    NAME varchar(50) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y'
);
ALTER TABLE WORK_GROUP ADD CONSTRAINT WORK_GROUP_PK PRIMARY KEY (WORK_GROUP_ID);


ALTER TABLE ACTION_CODE ADD CONSTRAINT ACTION_CODE_FK1 FOREIGN KEY (ACTION_TYPE_ID)
	REFERENCES ACTION_TYPE (ACTION_TYPE_ID);
ALTER TABLE ACTION_CODE ADD CONSTRAINT ACTION_CODE_FK2 FOREIGN KEY (AREA_ID)
	REFERENCES AREA (AREA_ID);
ALTER TABLE ACTION_CODE ADD CONSTRAINT ACTION_CODE_FK3 FOREIGN KEY (TEMPLATE_ID)
	REFERENCES TEMPLATE (TEMPLATE_ID);
ALTER TABLE ACTION_CODE ADD CONSTRAINT ACTION_CODE_FK4 FOREIGN KEY (WORK_GROUP_ID)
	REFERENCES WORK_GROUP (WORK_GROUP_ID);
ALTER TABLE ACTION_CODE ADD CONSTRAINT ACTION_CODE_FK5 FOREIGN KEY (JOB_TYPE_ID) REFERENCES JOB_TYPE (JOB_TYPE_ID);
ALTER TABLE ACTION_CODE ADD CONSTRAINT ACTION_CODE_FK6 FOREIGN KEY(DOCUMENT_TEMPLATE_ID) REFERENCES TEMPLATE(TEMPLATE_ID);
ALTER TABLE ACTION_CODE ADD CONSTRAINT ACTION_CODE_UK1 UNIQUE (CODE);

CREATE INDEX ACTION_CODE_IDX1 ON ACTION_CODE (WORK_GROUP_ID);

ALTER TABLE ACTION_OUTCOME ADD CONSTRAINT ACTION_OUTCOME_UK1 UNIQUE (NAME);

ALTER TABLE ACTION_TYPE ADD CONSTRAINT ACTION_TYPE_UK1 UNIQUE (NAME);

ALTER TABLE ACTION_WORKFLOW ADD CONSTRAINT ACTION_WORKFLOW_FK1 FOREIGN KEY (ACTION_CODE_ID)
	REFERENCES ACTION_CODE (ACTION_CODE_ID);
ALTER TABLE ACTION_WORKFLOW ADD CONSTRAINT ACTION_WORKFLOW_FK2 FOREIGN KEY (ACTION_OUTCOME_ID)
	REFERENCES ACTION_OUTCOME (ACTION_OUTCOME_ID);
ALTER TABLE ACTION_WORKFLOW ADD CONSTRAINT ACTION_WORKFLOW_FK3 FOREIGN KEY (NEXT_ACTION_CODE_ID)
	REFERENCES ACTION_CODE (ACTION_CODE_ID);

ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_FK1 FOREIGN KEY (STATE)
	REFERENCES STATE (STATE);

ALTER TABLE ALARM_PANEL ADD CONSTRAINT ALARM_PANEL_FK1 FOREIGN KEY (FILE_ID)
	REFERENCES FILES (FILE_ID);
ALTER TABLE ALARM_PANEL ADD CONSTRAINT ALARM_PANEL_FK2 FOREIGN KEY (SUPPLIER_ID)
	REFERENCES SUPPLIER (SUPPLIER_ID);

ALTER TABLE ARCHIVE ADD CONSTRAINT ARCHIVE_PK PRIMARY KEY (ARCHIVE_ID);
ALTER TABLE ARCHIVE ADD CONSTRAINT ARCHIVE_UK1 UNIQUE (BOX_CODE);

ALTER TABLE AREA ADD CONSTRAINT AREA_FK1 FOREIGN KEY (REGION_ID)
	REFERENCES REGION (REGION_ID);
ALTER TABLE AREA ADD CONSTRAINT AREA_FK2 FOREIGN KEY (CONTACT_ID)
	REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE AREA ADD CONSTRAINT AREA_FK3 FOREIGN KEY (ADDRESS_ID)
	REFERENCES ADDRESS (ADDRESS_ID);
-- ALTER TABLE AREA DROP CONSTRAINT AREA_UK1;
ALTER TABLE AREA ADD CONSTRAINT AREA_UK1 UNIQUE (NAME, REGION_ID, ACTIVE);

ALTER TABLE ASE_CHANGE ADD CONSTRAINT ASE_CHANGE_FK1 FOREIGN KEY (ASE_FILE_ID)
    REFERENCES ASE_FILE (ASE_FILE_ID);

ALTER TABLE ASE_CHANGE_SUPPLIER ADD CONSTRAINT ASE_CHANGE_SUPPLIER_FK1 FOREIGN KEY (ASE_CHANGE_ID)
    REFERENCES ASE_CHANGE (ASE_CHANGE_ID);
ALTER TABLE ASE_CHANGE_SUPPLIER ADD CONSTRAINT ASE_CHANGE_SUPPLIER_FK2 FOREIGN KEY (SUPPLIER_ID)
    REFERENCES SUPPLIER (SUPPLIER_ID);
ALTER TABLE ASE_CHANGE_SUPPLIER ADD CONSTRAINT ASE_CHANGE_SUPPLIER_FK3 FOREIGN KEY (ASE_CONN_TYPE_ID)
    REFERENCES ASE_CONN_TYPE (ASE_CONN_TYPE_ID);

ALTER TABLE ASE_CONN ADD CONSTRAINT ASE_CONN_FK1 FOREIGN KEY (ASE_FILE_ID)
    REFERENCES ASE_FILE (ASE_FILE_ID);
ALTER TABLE ASE_CONN ADD CONSTRAINT ASE_CONN_FK2 FOREIGN KEY (ASE_CONN_TYPE_ID)
    REFERENCES ASE_CONN_TYPE (ASE_CONN_TYPE_ID);
ALTER TABLE ASE_CONN ADD CONSTRAINT ASE_CONN_FK3 FOREIGN KEY (SEC_ASE_CONN_TYPE_ID)
    REFERENCES ASE_CONN_TYPE (ASE_CONN_TYPE_ID);

ALTER TABLE ASE_CONN_TYPE ADD CONSTRAINT ASE_CONN_TYPE_UK1 UNIQUE (NAME);

ALTER TABLE ASE_FILE ADD CONSTRAINT ASE_FILE_FK1 FOREIGN KEY (FILE_ID)
    REFERENCES FILES (FILE_ID);
ALTER TABLE ASE_FILE ADD CONSTRAINT ASE_FILE_FK2 FOREIGN KEY (ASE_TYPE_ID)
    REFERENCES ASE_TYPE (ASE_TYPE_ID);

ALTER TABLE ASE_SUPPLIER ADD CONSTRAINT ASE_SUPPLIER_FK1 FOREIGN KEY (ASE_FILE_ID)
    REFERENCES ASE_FILE (ASE_FILE_ID);
ALTER TABLE ASE_SUPPLIER ADD CONSTRAINT ASE_SUPPLIER_FK2 FOREIGN KEY (SUPPLIER_ID)
    REFERENCES SUPPLIER (SUPPLIER_ID);

ALTER TABLE ASE_TYPE ADD CONSTRAINT ASE_TYPE_UK1 UNIQUE (NAME);

ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_FK1 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID)
ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_FK2 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID);
-- ase key invoice - will be renamed to ASE_KEY_INVOICE in JMS.01.39.sql
ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_FK3 FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (INVOICE_ID);
ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_FK4 FOREIGN KEY (SENT_METHOD_ID) REFERENCES SENT_METHOD (SENT_METHOD_ID);
ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_FK5 FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD (PAYMENT_METHOD_ID);
ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_FK6 FOREIGN KEY (ASE_KEY_ORDER_ID) REFERENCES ASE_KEY_ORDER (ASE_KEY_ORDER_ID);
ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_FK7 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);

ALTER TABLE ASE_KEY_INVOICE ADD CONSTRAINT ASE_KEY_INVOICE_FK1 FOREIGN KEY (AUTHORISED_BY) REFERENCES USERS (USER_ID);

ALTER TABLE BUILDING ADD CONSTRAINT BUILDING_FK1 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID);
ALTER TABLE BUILDING ADD CONSTRAINT BUILDING_FK2 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID);
ALTER TABLE BUILDING ADD CONSTRAINT BUILDING_FK3 FOREIGN KEY (NEXT_BUILDING_ID) REFERENCES BUILDING (BUILDING_ID);
ALTER TABLE BUILDING ADD CONSTRAINT BUILDING_FK4 FOREIGN KEY (ARCH_BY) REFERENCES USERS (USER_ID);
-- ALTER TABLE BUILDING ADD CONSTRAINT BUILDING_UK1 UNIQUE (NAME);
ALTER TABLE BUILDING ADD CONSTRAINT BUILDING_FK5 FOREIGN KEY (ESCAD_BUILDING_ID) REFERENCES BUILDING_ALT (BUILDING_ALT_ID);
ALTER TABLE BUILDING ADD CONSTRAINT BUILDING_FK6 FOREIGN KEY (MASTERMIND_BUILDING_ID) REFERENCES BUILDING_ALT (BUILDING_ALT_ID);

CREATE INDEX BUILDING_IDX1 ON BUILDING (FILE_ID);
CREATE INDEX BUILDING_IDX2 ON BUILDING (ADDRESS_ID);

ALTER TABLE BUILDING_ALT ADD CONSTRAINT BUILDING_ALT_FK1 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID);
ALTER TABLE BUILDING_ALT ADD CONSTRAINT BUILDING_ALT_FK2 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID);

ALTER TABLE BUILDING_CONTACT ADD CONSTRAINT BUILDING_CONTACT_FK1 FOREIGN KEY (FILE_ID)
	REFERENCES FILES (FILE_ID);
ALTER TABLE BUILDING_CONTACT ADD CONSTRAINT BUILDING_CONTACT_FK2 FOREIGN KEY (CONTACT_ID)
	REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE BUILDING_CONTACT ADD CONSTRAINT BUILDING_CONTACT_FK3 FOREIGN KEY (BUILDING_CONTACT_TYPE_ID)
	REFERENCES BUILDING_CONTACT_TYPE (BUILDING_CONTACT_TYPE_ID);

ALTER TABLE BUILDING_CONTACT_TYPE ADD CONSTRAINT BUILDING_CONTACT_TYPE_UK1 UNIQUE (NAME);

ALTER TABLE CONTACT ADD CONSTRAINT CONTACT_FK1 FOREIGN KEY (SALUTATION)
	REFERENCES SALUTATION (SALUTATION);
-- ALTER TABLE CONTACT ADD CONSTRAINT CONTACT_UK1 UNIQUE (EMAIL);

ALTER TABLE DBVERSION ADD CONSTRAINT DBVERSION_FK1 FOREIGN KEY (PREV_DBVERSION)
	REFERENCES DBVERSION (DBVERSION);

ALTER TABLE DOC_CHK_LIST ADD CONSTRAINT DOC_CHK_LIST_FK1 FOREIGN KEY (TEMPLATE_ID)
	REFERENCES TEMPLATE (TEMPLATE_ID);

ALTER TABLE FCA ADD CONSTRAINT FCA_FK1 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID);
ALTER TABLE FCA ADD CONSTRAINT FCA_FK2 FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID);
ALTER TABLE FCA ADD CONSTRAINT FCA_FK3 FOREIGN KEY (STATION_CODE) REFERENCES STATION (STATION_CODE);
ALTER TABLE FCA ADD CONSTRAINT FCA_FK4 FOREIGN KEY (AREA_ID) REFERENCES AREA (AREA_ID);
--According to the ANSI standards SQL:92, SQL:1999, and SQL:2003,
--a UNIQUE constraint should disallow duplicate non-NULL values,
--but allow multiple NULL values.
--SQL Server has always implemented a crippled version of this,
--allowing a single NULL but disallowing multiple NULL values.
--ALTER TABLE FCA ADD CONSTRAINT FCA_UK1 UNIQUE (FILE_ID) WITH ANSI_NULLS = OFF;
--ALTER TABLE FCA DROP CONSTRAINT FCA_UK1;

CREATE INDEX FCA_IDX2 ON FCA (FILE_ID);

ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_FK1 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID);
ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_FK2 FOREIGN KEY (ACTION_CODE_ID) REFERENCES ACTION_CODE (ACTION_CODE_ID);
ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_FK3 FOREIGN KEY (ACTION_OUTCOME_ID) REFERENCES ACTION_OUTCOME (ACTION_OUTCOME_ID);
ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_FK4 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_FK5 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_FK6 FOREIGN KEY (RESPONSIBLE_USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_FK7 FOREIGN KEY (PARENT_ACTION_ID) REFERENCES FILE_ACTION (FILE_ACTION_ID);
ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_FK8 FOREIGN KEY (PARENT_JOB_ACTION_ID) REFERENCES JOB_ACTION (JOB_ACTION_ID);
ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_FK9 FOREIGN KEY(ATTACHMENT_ID) REFERENCES DOCUMENT(DOCUMENT_ID);

CREATE INDEX FILE_ACTION_IDX1 ON FILE_ACTION (FILE_ID);
CREATE INDEX FILE_ACTION_IDX2 ON FILE_ACTION (ACTION_CODE_ID);
CREATE INDEX FILE_ACTION_IDX3 ON FILE_ACTION (CONTACT_ID);
CREATE INDEX FILE_ACTION_IDX4 ON FILE_ACTION (RESPONSIBLE_USER_ID);

ALTER TABLE FILE_ARCHIVE ADD CONSTRAINT FILE_ARCHIVE_PK PRIMARY KEY (FILE_ID);
ALTER TABLE FILE_ARCHIVE ADD CONSTRAINT FILE_ARCHIVE_FK1 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID);
ALTER TABLE FILE_ARCHIVE ADD CONSTRAINT FILE_ARCHIVE_FK2 FOREIGN KEY (ARCHIVE_ID) REFERENCES ARCHIVE (ARCHIVE_ID);

ALTER TABLE FILE_DOC ADD CONSTRAINT FILE_DOC_FK1 FOREIGN KEY (FILE_ID)
	REFERENCES FILES (FILE_ID);
ALTER TABLE FILE_DOC ADD CONSTRAINT FILE_DOC_FK2 FOREIGN KEY (DOC_TYPE_ID)
	REFERENCES DOC_TYPE (DOC_TYPE_ID);
ALTER TABLE FILE_DOC ADD CONSTRAINT FILE_DOC_FK3 FOREIGN KEY (DOCUMENT_ID)
	REFERENCES DOCUMENT (DOCUMENT_ID);

ALTER TABLE FILE_DOC_CHK_LIST ADD CONSTRAINT FILE_DOC_CHK_LIST_FK1 FOREIGN KEY (FILE_ID)
	REFERENCES FILES (FILE_ID);
ALTER TABLE FILE_DOC_CHK_LIST ADD CONSTRAINT FILE_DOC_CHK_LIST_FK2 FOREIGN KEY (DOC_CHK_LIST_ID)
	REFERENCES DOC_CHK_LIST (DOC_CHK_LIST_ID);

ALTER TABLE FILES ADD CONSTRAINT FILES_FK1 FOREIGN KEY (FILE_STATUS_ID) REFERENCES FILE_STATUS (FILE_STATUS_ID);
--ALTER TABLE FILES ADD CONSTRAINT FILES_FK2 FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID);
--ALTER TABLE FILES DROP CONSTRAINT FILES_FK2;
ALTER TABLE FILES ADD CONSTRAINT FILES_FK3 FOREIGN KEY (MAIL_METHOD_ID) REFERENCES MAIL_METHOD (MAIL_METHOD_ID);
ALTER TABLE FILES ADD CONSTRAINT FILES_FK4 FOREIGN KEY (FILE_TYPE_ID) REFERENCES FILE_TYPE (FILE_TYPE_ID);

CREATE INDEX FILES_IDX1 ON FILES (FILE_TYPE_ID);
CREATE INDEX FILES_IDX2 ON FILES (FILE_STATUS_ID);

ALTER TABLE FILE_AUDIT ADD CONSTRAINT FILE_AUDIT_FK1 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID);
ALTER TABLE FILE_AUDIT ADD CONSTRAINT FILE_AUDIT_FK2 FOREIGN KEY (AUDIT_STATUS_ID) REFERENCES AUDIT_STATUS (AUDIT_STATUS_ID);
ALTER TABLE FILE_AUDIT ADD CONSTRAINT FILE_AUDIT_FK3 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);

ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK1 FOREIGN KEY (INVOICE_TYPE_ID) REFERENCES INVOICE_TYPE (INVOICE_TYPE_ID);
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK2 FOREIGN KEY (INVOICE_AREA_ID) REFERENCES INVOICE_AREA (INVOICE_AREA_ID);
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK3 FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID);
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK4 FOREIGN KEY (BRIGADE_ID) REFERENCES BRIGADE (BRIGADE_ID);
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK5 FOREIGN KEY (INVOICE_BATCH_ID) REFERENCES INVOICE_BATCH (INVOICE_BATCH_ID);

ALTER TABLE INVOICE_BATCH ADD CONSTRAINT INVOICE_BATCH_FK1 FOREIGN KEY (INVOICE_AREA_ID) REFERENCES INVOICE_AREA (INVOICE_AREA_ID);
ALTER TABLE INVOICE_BATCH ADD CONSTRAINT INVOICE_BATCH_FK2 FOREIGN KEY (INVOICE_TYPE_ID) REFERENCES INVOICE_TYPE (INVOICE_TYPE_ID);

ALTER TABLE INVOICE_TYPE ADD CONSTRAINT INVOICE_TYPE_FK1 FOREIGN KEY (INVOICE_AREA_ID)
    REFERENCES INVOICE_AREA (INVOICE_AREA_ID);

ALTER TABLE ISOLATION_HISTORY ADD CONSTRAINT ISOLATION_HISTORY_PK PRIMARY KEY (ISOLATION_HISTORY_ID);
ALTER TABLE ISOLATION_HISTORY ADD CONSTRAINT ISOLATION_HISTORY_FK1 FOREIGN KEY (FCA_NO) REFERENCES FCA (FCA_NO);
CREATE INDEX ISOLATION_HISTORY_IDX1 ON ISOLATION_HISTORY (FCA_NO);
CREATE INDEX ISOLATION_HISTORY_IDX2 ON ISOLATION_HISTORY (FCA_NO, INPUT, ISOLATION_DATE, DE_ISOLATION_DATE);

ALTER TABLE JOBS ADD CONSTRAINT JOBS_FK1 FOREIGN KEY (JOB_TYPE_ID) REFERENCES JOB_TYPE (JOB_TYPE_ID);
ALTER TABLE JOBS ADD CONSTRAINT JOBS_FK2 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID);
ALTER TABLE JOBS ADD CONSTRAINT JOBS_FK3 FOREIGN KEY (JOB_REQUEST_ID) REFERENCES JOB_REQUEST (JOB_REQUEST_ID);
ALTER TABLE JOBS ADD CONSTRAINT JOBS_FK4 FOREIGN KEY (FCA_NO) REFERENCES FCA (FCA_NO);
ALTER TABLE JOBS ADD CONSTRAINT JOBS_FK5 FOREIGN KEY (RESPONSIBLE_USER_ID) REFERENCES USERS (USER_ID);

CREATE INDEX JOBS_IDX1 ON JOBS (STATUS);
CREATE INDEX JOBS_IDX2 ON JOBS (JOB_TYPE_ID);
CREATE INDEX JOBS_IDX3 ON JOBS (FILE_ID);
CREATE INDEX JOBS_IDX4 ON JOBS (FCA_NO);
CREATE INDEX JOBS_IDX5 ON JOBS (RESPONSIBLE_USER_ID);

ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_FK1 FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID);
ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_FK2 FOREIGN KEY (ACTION_CODE_ID) REFERENCES ACTION_CODE (ACTION_CODE_ID);
ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_FK3 FOREIGN KEY (ACTION_OUTCOME_ID) REFERENCES ACTION_OUTCOME (ACTION_OUTCOME_ID);
ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_FK4 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);
ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_FK5 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_FK6 FOREIGN KEY (RESPONSIBLE_USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_FK7 FOREIGN KEY (PARENT_ACTION_ID) REFERENCES JOB_ACTION (JOB_ACTION_ID);
ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_FK8 FOREIGN KEY (PARENT_FILE_ACTION_ID) REFERENCES FILE_ACTION (FILE_ACTION_ID);
ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_FK9 FOREIGN KEY(ATTACHMENT_ID) REFERENCES DOCUMENT(DOCUMENT_ID);

CREATE INDEX JOB_ACTION_IDX1 ON JOB_ACTION (JOB_ID);
CREATE INDEX JOB_ACTION_IDX2 ON JOB_ACTION (ACTION_CODE_ID);
CREATE INDEX JOB_ACTION_IDX3 ON JOB_ACTION (CONTACT_ID);
CREATE INDEX JOB_ACTION_IDX4 ON JOB_ACTION (RESPONSIBLE_USER_ID);

ALTER TABLE JOB_DOC ADD CONSTRAINT JOB_DOC_FK1 FOREIGN KEY (JOB_ID)
	REFERENCES JOBS (JOB_ID);
ALTER TABLE JOB_DOC ADD CONSTRAINT JOB_DOC_FK2 FOREIGN KEY (DOC_TYPE_ID)
	REFERENCES DOC_TYPE (DOC_TYPE_ID);
ALTER TABLE JOB_DOC ADD CONSTRAINT JOB_DOC_FK3 FOREIGN KEY (DOCUMENT_ID)
	REFERENCES DOCUMENT (DOCUMENT_ID);

ALTER TABLE JOB_REQUEST ADD CONSTRAINT JOB_REQUEST_FK1 FOREIGN KEY (JOB_TYPE_ID)
	REFERENCES JOB_TYPE (JOB_TYPE_ID);
ALTER TABLE JOB_REQUEST ADD CONSTRAINT JOB_REQUEST_FK2 FOREIGN KEY (FCA_NO)
	REFERENCES FCA (FCA_NO);
ALTER TABLE JOB_REQUEST ADD CONSTRAINT JOB_REQUEST_FK3 FOREIGN KEY (REQUESTED_BY)
	REFERENCES USERS (USER_ID);
ALTER TABLE JOB_REQUEST ADD CONSTRAINT JOB_REQUEST_FK4 FOREIGN KEY (ACCEPTED_BY)
	REFERENCES USERS (USER_ID);

ALTER TABLE JOB_TYPE ADD CONSTRAINT JOB_TYPE_FK1 FOREIGN KEY (CLOSE_JOB_SECURITY_GROUP_ID)
	REFERENCES SECURITY_GROUP (SECURITY_GROUP_ID);
ALTER TABLE JOB_TYPE ADD CONSTRAINT JOB_TYPE_FK2 FOREIGN KEY (ACTION_CODE_ID)
	REFERENCES ACTION_CODE (ACTION_CODE_ID);
ALTER TABLE JOB_TYPE ADD CONSTRAINT JOB_TYPE_FK3 FOREIGN KEY (WORK_GROUP_ID)
	REFERENCES WORK_GROUP (WORK_GROUP_ID);
ALTER TABLE JOB_TYPE ADD CONSTRAINT JOB_TYPE_UK1 UNIQUE (NAME);

ALTER TABLE KEY_RECEIPT ADD CONSTRAINT KEY_RECEIPT_FK1 FOREIGN KEY (FILE_ID)
	REFERENCES FILES (FILE_ID);
ALTER TABLE KEY_RECEIPT ADD CONSTRAINT KEY_RECEIPT_UK1 UNIQUE (KEY_RECEIPT_NO);

ALTER TABLE KEY_REG ADD CONSTRAINT KEY_REG_FK1 FOREIGN KEY (FILE_ID)
	REFERENCES FILES (FILE_ID);
ALTER TABLE KEY_REG ADD CONSTRAINT KEY_REG_UK1 UNIQUE (KEY_NO);

ALTER TABLE MAIL_BATCH_FILE ADD CONSTRAINT MAIL_BATCH_FILE_FK1 FOREIGN KEY (MAIL_BATCH_ID) REFERENCES MAIL_BATCH (MAIL_BATCH_ID);
ALTER TABLE MAIL_BATCH_FILE ADD CONSTRAINT MAIL_BATCH_FILE_FK2 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID);
ALTER TABLE MAIL_BATCH_FILE ADD CONSTRAINT MAIL_BATCH_FILE_FK3 FOREIGN KEY (FILE_ACTION_ID) REFERENCES FILE_ACTION (FILE_ACTION_ID);
ALTER TABLE MAIL_BATCH_FILE ADD CONSTRAINT MAIL_BATCH_FILE_FK4 FOREIGN KEY (JOB_ACTION_ID) REFERENCES JOB_ACTION (JOB_ACTION_ID);
ALTER TABLE MAIL_BATCH_FILE ADD CONSTRAINT MAIL_BATCH_FILE_FK5 FOREIGN KEY (STATUS_ID) REFERENCES MAIL_BATCH_STATUS (MAIL_BATCH_STATUS_ID);
ALTER TABLE MAIL_BATCH_FILE ADD CONSTRAINT MAIL_BATCH_FILE_UK1 UNIQUE (MAIL_BATCH_ID, FILE_ID);

ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_PK PRIMARY KEY (MAIL_REGISTER_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK1 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID)
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK2 FOREIGN KEY (MAIL_TYPE_ID) REFERENCES MAIL_TYPE (MAIL_TYPE_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK3 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK4 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK5 FOREIGN KEY (WORK_GROUP_ID) REFERENCES WORK_GROUP (WORK_GROUP_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK6 FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);

ALTER TABLE FILES ADD CONSTRAINT FILES_FK3 FOREIGN KEY (MAIL_METHOD_ID) REFERENCES MAIL_METHOD (MAIL_METHOD_ID);

ALTER TABLE OWNER ADD CONSTRAINT OWNER_FK1 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID);
ALTER TABLE OWNER ADD CONSTRAINT OWNER_FK2 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE OWNER ADD CONSTRAINT OWNER_FK3 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID);
ALTER TABLE OWNER ADD CONSTRAINT OWNER_FK4 FOREIGN KEY (NEXT_OWNER_ID) REFERENCES OWNER (OWNER_ID);
ALTER TABLE OWNER ADD CONSTRAINT OWNER_FK5 FOREIGN KEY (ARCH_BY) REFERENCES USERS (USER_ID);
ALTER TABLE OWNER ADD CONSTRAINT OWNER_FK6 FOREIGN KEY (OWNER_TYPE_ID) REFERENCES OWNER_TYPE (OWNER_TYPE_ID);
ALTER TABLE OWNER ADD CONSTRAINT OWNER_UK1 UNIQUE (FILE_ID, OWNER_TYPE_ID);

CREATE INDEX OWNER_IDX1 ON OWNER (OWNER_TYPE_ID);
CREATE INDEX OWNER_IDX2 ON OWNER (FILE_ID);
CREATE INDEX OWNER_IDX3 ON OWNER (CONTACT_ID);

ALTER TABLE REGION ADD CONSTRAINT REGION_FK1 FOREIGN KEY (CONTACT_ID)
	REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE REGION ADD CONSTRAINT REGION_FK2 FOREIGN KEY (ADDRESS_ID)
	REFERENCES ADDRESS (ADDRESS_ID);
ALTER TABLE REGION ADD CONSTRAINT REGION_UK1 UNIQUE (NAME);

ALTER TABLE REPORT_DOC ADD CONSTRAINT REPORT_DOC_FK1 FOREIGN KEY (DOC_TYPE_ID)
	REFERENCES DOC_TYPE (DOC_TYPE_ID);
ALTER TABLE REPORT_DOC ADD CONSTRAINT REPORT_DOC_FK2 FOREIGN KEY (DOCUMENT_ID)
	REFERENCES DOCUMENT (DOCUMENT_ID);
ALTER TABLE REPORT_DOC ADD CONSTRAINT REPORT_DOC_FK3 FOREIGN KEY (TEMPLATE_ID)
	REFERENCES TEMPLATE (TEMPLATE_ID);

ALTER TABLE RFI ADD CONSTRAINT RFI_FK1 FOREIGN KEY (FILE_ID)
	REFERENCES FILES (FILE_ID);
ALTER TABLE RFI ADD CONSTRAINT RFI_FK2 FOREIGN KEY (FILE_ACTION_ID)
	REFERENCES FILE_ACTION (FILE_ACTION_ID);

ALTER TABLE SAP_HEADER ADD CONSTRAINT SAP_HEADER_FK1 FOREIGN KEY (FILE_ID)
	REFERENCES FILES (FILE_ID);

ALTER TABLE SCHEDULED_TASK_HISTORY ADD CONSTRAINT SCHEDULED_TASK_HISTORY_FK1 FOREIGN KEY (SCHEDULED_TASK_ID) REFERENCES SCHEDULED_TASK (SCHEDULED_TASK_ID);

ALTER TABLE SCHEDULED_TASK_HISTORY_ITEM ADD CONSTRAINT SCHEDULED_TASK_HISTORY_ITEM_FK1 FOREIGN KEY (SCHEDULED_TASK_HISTORY_ID) REFERENCES SCHEDULED_TASK_HISTORY (SCHEDULED_TASK_HISTORY_ID);

ALTER TABLE STAKE_HOLDER ADD CONSTRAINT STAKE_HOLDER_FK1 FOREIGN KEY (STAKE_HOLDER_TYPE_ID)
	REFERENCES STAKE_HOLDER_TYPE (STAKE_HOLDER_TYPE_ID);
ALTER TABLE STAKE_HOLDER ADD CONSTRAINT STAKE_HOLDER_FK2 FOREIGN KEY (REGION_ID)
	REFERENCES REGION (REGION_ID);
ALTER TABLE STAKE_HOLDER ADD CONSTRAINT STAKE_HOLDER_FK3 FOREIGN KEY (CONTACT_ID)
	REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE STAKE_HOLDER ADD CONSTRAINT STAKE_HOLDER_FK4 FOREIGN KEY (ADDRESS_ID)
	REFERENCES ADDRESS (ADDRESS_ID);

ALTER TABLE STATION ADD CONSTRAINT STATION_FK1 FOREIGN KEY (AREA_ID)
	REFERENCES AREA (AREA_ID);
ALTER TABLE STATION ADD CONSTRAINT STATION_FK2 FOREIGN KEY (CONTACT_ID)
	REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE STATION ADD CONSTRAINT STATION_FK3 FOREIGN KEY (ADDRESS_ID)
	REFERENCES ADDRESS (ADDRESS_ID);

ALTER TABLE STAFF_LEAVE ADD CONSTRAINT STAFF_LEAVE_FK1 FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE STAFF_LEAVE ADD CONSTRAINT STAFF_LEAVE_FK2 FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES LEAVE_TYPE (LEAVE_TYPE_ID);
ALTER TABLE STAFF_LEAVE ADD CONSTRAINT STAFF_LEAVE_FK3 FOREIGN KEY (STATUS_ID) REFERENCES LEAVE_STATUS (LEAVE_STATUS_ID);
ALTER TABLE STAFF_LEAVE ADD CONSTRAINT STAFF_LEAVE_UK1 UNIQUE (USER_ID, LEAVE_DATE);

ALTER TABLE SUB_PANEL ADD CONSTRAINT SUB_PANEL_FK1 FOREIGN KEY (ASE_FILE_ID)
	REFERENCES ASE_FILE (ASE_FILE_ID);
ALTER TABLE SUB_PANEL ADD CONSTRAINT SUB_PANEL_FK2 FOREIGN KEY (ADDRESS_ID)
	REFERENCES ADDRESS (ADDRESS_ID);

ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_FK1 FOREIGN KEY (SUPPLIER_TYPE_ID)
	REFERENCES SUPPLIER_TYPE (SUPPLIER_TYPE_ID);
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_FK2 FOREIGN KEY (REGION_ID)
	REFERENCES REGION (REGION_ID);
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_FK3 FOREIGN KEY (CONTACT_ID)
	REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_FK4 FOREIGN KEY (ADDRESS_ID)
	REFERENCES ADDRESS (ADDRESS_ID);
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_FK5 FOREIGN KEY (POST_ADDRESS_ID)
	REFERENCES ADDRESS (ADDRESS_ID);
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_FK6 FOREIGN KEY (MASTER_SUPPLIER_ID)
	REFERENCES SUPPLIER (SUPPLIER_ID);
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_UK1 UNIQUE (NAME);
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_UK2 UNIQUE (LEGAL_NAME);
ALTER TABLE SUPPLIER ADD CONSTRAINT SUPPLIER_UK3 UNIQUE (ABN);

ALTER TABLE SUPPLIER_TYPE ADD CONSTRAINT SUPPLIER_TYPE_UK1 UNIQUE (NAME);

ALTER TABLE SUPPLIER_TYPE_MATCH ADD CONSTRAINT SUPPLIER_TYPE_MATCH_FK1 FOREIGN KEY (SUPPLIER_ID)
	REFERENCES SUPPLIER (SUPPLIER_ID);
ALTER TABLE SUPPLIER_TYPE_MATCH ADD CONSTRAINT SUPPLIER_TYPE_MATCH_FK2 FOREIGN KEY (SUPPLIER_TYPE_ID)
	REFERENCES SUPPLIER_TYPE (SUPPLIER_TYPE_ID);

ALTER TABLE SYSTEM_ACCESS ADD CONSTRAINT SYSTEM_ACCESS_FK1 FOREIGN KEY (SECURITY_GROUP_ID)
	REFERENCES SECURITY_GROUP (SECURITY_GROUP_ID);
ALTER TABLE SYSTEM_ACCESS ADD CONSTRAINT SYSTEM_ACCESS_FK2 FOREIGN KEY (SYSTEM_FUNCTION_ID)
	REFERENCES SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID);

ALTER TABLE TEMPLATE ADD CONSTRAINT TEMPLATE_FK1 FOREIGN KEY (TEMPLATE_TYPE_ID)
	REFERENCES TEMPLATE_TYPE (TEMPLATE_TYPE_ID);
ALTER TABLE TEMPLATE ADD CONSTRAINT TEMPLATE_FK2 FOREIGN KEY(CONFIG_DOCUMENT_ID) REFERENCES DOCUMENT(DOCUMENT_ID);

ALTER TABLE TEMPLATE_TYPE ADD CONSTRAINT TEMPLATE_TYPE_UK1 UNIQUE (NAME);

ALTER TABLE USERS ADD CONSTRAINT USERS_FK1 FOREIGN KEY (CONTACT_ID)
	REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE USERS ADD CONSTRAINT USERS_FK2 FOREIGN KEY (USER_TYPE_ID)
	REFERENCES USER_TYPE (USER_TYPE_ID);
ALTER TABLE USERS ADD CONSTRAINT USERS_FK3 FOREIGN KEY (SECURITY_GROUP_ID)
	REFERENCES SECURITY_GROUP (SECURITY_GROUP_ID);
ALTER TABLE USERS ADD CONSTRAINT USERS_FK4 FOREIGN KEY (CREATED_BY)
	REFERENCES USERS (USER_ID);
ALTER TABLE USERS ADD CONSTRAINT USERS_FK5 FOREIGN KEY (UPDATED_BY)
	REFERENCES USERS (USER_ID);
ALTER TABLE USERS ADD CONSTRAINT USERS_FK6 FOREIGN KEY (SUPPLIER_ID)
	REFERENCES SUPPLIER (SUPPLIER_ID);
ALTER TABLE USERS ADD CONSTRAINT USERS_UK1 UNIQUE (LOGIN);

ALTER TABLE USERS_WORKGROUP ADD CONSTRAINT USERS_WORKGROUP_FK1 FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE USERS_WORKGROUP ADD CONSTRAINT USERS_WORKGROUP_FK2 FOREIGN KEY (WORK_GROUP_ID) REFERENCES WORK_GROUP (WORK_GROUP_ID);
