sp_rename INVOICE, ASE_KEY_INVOICE
GO
sp_rename INVOICE_PK, ASE_KEY_INVOICE_PK
GO
sp_rename INVOICE_FK1, ASE_KEY_INVOICE_FK1
GO

CREATE TABLE BRIGADE (
    BRIGADE_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    SAP_CUST_NO numeric(11, 0) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE BRIGADE ADD CONSTRAINT BRIGADE_PK PRIMARY KEY (BRIGADE_ID);
-- Rural Brigade Data (Managed By Users)

CREATE TABLE INVOICE_AREA (
    INVOICE_AREA_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    DESCRIPTION varchar(250) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE INVOICE_AREA ADD CONSTRAINT INVOICE_AREA_PK PRIMARY KEY (INVOICE_AREA_ID);
-- Main Invoicing Areas (CSO, TEM, RFS, MID ect)
INSERT INTO INVOICE_AREA (INVOICE_AREA_ID, NAME, DESCRIPTION) VALUES (1, 'CSO', 'CSO');
INSERT INTO INVOICE_AREA (INVOICE_AREA_ID, NAME, DESCRIPTION) VALUES (2, 'TEM', 'TEM');
INSERT INTO INVOICE_AREA (INVOICE_AREA_ID, NAME, DESCRIPTION) VALUES (3, 'RFS', 'RFS');
INSERT INTO INVOICE_AREA (INVOICE_AREA_ID, NAME, DESCRIPTION) VALUES (4, 'MID', 'MID');

CREATE TABLE INVOICE_TYPE (
    INVOICE_TYPE_ID numeric(11, 0) NOT NULL,
    INVOICE_AREA_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE INVOICE_TYPE ADD CONSTRAINT INVOICE_TYPE_PK PRIMARY KEY (INVOICE_TYPE_ID);
ALTER TABLE INVOICE_TYPE ADD CONSTRAINT INVOICE_TYPE_FK1 FOREIGN KEY (INVOICE_AREA_ID) REFERENCES INVOICE_AREA (INVOICE_AREA_ID);
-- Invoice Types eg: Assessment, Inspection. Filter will old values B, S, N (BAO, SAO, NONE) to filter the invoice types based on selection
INSERT INTO INVOICE_TYPE (INVOICE_TYPE_ID, INVOICE_AREA_ID, NAME) VALUES (1, 1, 'Assessment');

CREATE TABLE INVOICE_BATCH (
    INVOICE_BATCH_ID numeric(11, 0) NOT NULL,
    INVOICE_TYPE_ID numeric(11, 0) NOT NULL,
    INVOICE_AREA_ID numeric(11, 0) NOT NULL,
    FISCAL_YEAR numeric(4, 0) NOT NULL,
    MONTH numeric(2, 0) NOT NULL,
    DAY numeric(2, 0) NOT NULL,
    SEQUENCE numeric(9, 0) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE INVOICE_BATCH ADD CONSTRAINT INVOICE_BATCH_PK PRIMARY KEY (INVOICE_BATCH_ID);
ALTER TABLE INVOICE_BATCH ADD CONSTRAINT INVOICE_BATCH_FK1 FOREIGN KEY (INVOICE_AREA_ID) REFERENCES INVOICE_AREA (INVOICE_AREA_ID);
ALTER TABLE INVOICE_BATCH ADD CONSTRAINT INVOICE_BATCH_FK2 FOREIGN KEY (INVOICE_TYPE_ID) REFERENCES INVOICE_TYPE (INVOICE_TYPE_ID);

CREATE TABLE INVOICE (
    INVOICE_ID numeric(11, 0) IDENTITY(10001,1) NOT NULL,
    INVOICE_TYPE_ID numeric(11, 0) NOT NULL,
    INVOICE_AREA_ID numeric(11, 0) NOT NULL,
    FISCAL_YEAR numeric(4, 0) NOT NULL,
    REGION_ID numeric(11, 0) NULL,
    BRIGADE_ID numeric(11, 0) NULL,
    RECEIPT_BATCH varchar(8) NULL,
    DATE_RECEIVED datetime NOT NULL,
    DATE_ACTIONED datetime NULL,
    JOB_REFERENCE varchar(20) NULL,
    INCIDENT_DATE datetime NULL,
    SAP_CUST_NO numeric(11, 0) NULL,
    SAP_CUST_CREATE char(1) NOT NULL DEFAULT 'N',
    SAP_CUST_CHANGE char(1) NOT NULL DEFAULT 'N',
    SAP_CUST_UNBLOCK char(1) NOT NULL DEFAULT 'N',
    INVOICE_BATCH_ID numeric(11, 0) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_PK PRIMARY KEY (INVOICE_ID);
-- ALTER TABLE INVOICE DROP CONSTRAINT INVOICE_FK;
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK1 FOREIGN KEY (INVOICE_TYPE_ID) REFERENCES INVOICE_TYPE (INVOICE_TYPE_ID);
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK2 FOREIGN KEY (INVOICE_AREA_ID) REFERENCES INVOICE_AREA (INVOICE_AREA_ID);
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK3 FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID);
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK4 FOREIGN KEY (BRIGADE_ID) REFERENCES BRIGADE (BRIGADE_ID);
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK5 FOREIGN KEY (INVOICE_BATCH_ID) REFERENCES INVOICE_BATCH (INVOICE_BATCH_ID);

CREATE TABLE INVOICE_HEADER (
    INVOICE_HEADER_ID numeric(11, 0) IDENTITY NOT NULL,
    INVOICE_ID numeric(11, 0) NOT NULL,
    TRANSACTION_TYPE varchar(2) NOT NULL, -- DEFAULT 'AR',
    ROW_TYPE varchar(3) NOT NULL, -- DEFAULT 'HDR',
    SEQUENCE numeric(9, 0) NOT NULL,
    COMPANY_CODE numeric(9, 0) NOT NULL, -- DEFAULT 1121,
    DOCUMENT_DATE datetime NULL,
    POST_DATE datetime NULL,
    DOCUMENT_TYPE varchar(2) NOT NULL, -- DEFAULT 'ZD',
    CURRENCY varchar(3) NOT NULL, -- DEFAULT 'AUD',
    REFERENCE varchar(50) NOT NULL,
    HEADER_TEXT varchar(50) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE INVOICE_HEADER ADD CONSTRAINT INVOICE_HEADER_PK PRIMARY KEY (INVOICE_HEADER_ID);
ALTER TABLE INVOICE_HEADER ADD CONSTRAINT INVOICE_HEADER_FK1 FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (INVOICE_ID);

CREATE TABLE INVOICE_DATA (
    INVOICE_DATA_ID numeric(11, 0) IDENTITY NOT NULL,
    INVOICE_ID numeric(11, 0) NOT NULL,
    TRANSACTION_TYPE varchar(2) NOT NULL, -- DEFAULT 'AR',
    ROW_TYPE varchar(3) NOT NULL, -- DEFAULT 'ITM',
    SEQUENCE numeric(9, 0) NOT NULL,
    AMOUNT numeric(19,2) NOT NULL,
    DR_CR varchar(2) NOT NULL, -- DEFAULT 'DR',
    ITEM_TEXT varchar(50) NOT NULL, -- DEFAULT 'CHARGE FOR UNWANTED ALARM ACTIVATION',
    FCA_NO varchar(8) NULL, -- ASSIGNMENT
    SAP_CUST_NO numeric(11, 0) NOT NULL,
    PAYMENT_TERM varchar(10) NOT NULL,
    DUNNING_AREA varchar(10) NOT NULL, -- DEFAULT '06',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE INVOICE_DATA ADD CONSTRAINT INVOICE_DATA_PK PRIMARY KEY (INVOICE_DATA_ID);
ALTER TABLE INVOICE_DATA ADD CONSTRAINT INVOICE_DATA_FK1 FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (INVOICE_ID);
ALTER TABLE INVOICE_DATA ADD CONSTRAINT INVOICE_DATA_FK2 FOREIGN KEY (FCA_NO) REFERENCES FCA (FCA_NO);

CREATE TABLE INVOICE_GL_DATA (
    INVOICE_GL_DATA_ID numeric(11, 0) IDENTITY NOT NULL,
    INVOICE_ID numeric(11, 0) NOT NULL,
    TRANSACTION_TYPE varchar(2) NOT NULL, -- DEFAULT 'AR',
    ROW_TYPE varchar(3) NOT NULL, -- DEFAULT 'ITM',
    SEQUENCE numeric(9, 0) NOT NULL,
    GL_ACCOUNT numeric(11, 0) NOT NULL, -- DEFAULT 415104,
    COST_CENTER numeric(11, 0) NOT NULL, -- DEFAULT 6951005,
    TAX_CODE varchar(2) NOT NULL, -- DEFAULT 'SZ',
    AMOUNT numeric(19,2) NOT NULL,
    DR_CR varchar(2) NOT NULL, -- DEFAULT 'CR',
    ITEM_TEXT varchar(50) NOT NULL, -- DEFAULT 'CHARGE FOR UNWANTED ALARM ACTIVATION',
    FCA_NO varchar(8) NULL, -- ASSIGNMENT
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE INVOICE_GL_DATA ADD CONSTRAINT INVOICE_GL_DATA_PK PRIMARY KEY (INVOICE_GL_DATA_ID);
ALTER TABLE INVOICE_GL_DATA ADD CONSTRAINT INVOICE_GL_DATA_FK1 FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (INVOICE_ID);
ALTER TABLE INVOICE_GL_DATA ADD CONSTRAINT INVOICE_GL_DATA_FK2 FOREIGN KEY (FCA_NO) REFERENCES FCA (FCA_NO);

CREATE TABLE INVOICE_TEXT (
    INVOICE_TEXT_ID numeric(11, 0) IDENTITY NOT NULL,
    INVOICE_ID numeric(11, 0) NOT NULL,
    TRANSACTION_TYPE varchar(2) NOT NULL, -- DEFAULT 'AR',
    ROW_TYPE varchar(3) NOT NULL, -- DEFAULT 'ILT',
    SEQUENCE numeric(9, 0) NOT NULL,
    ITEM_TEXT varchar(1024) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE INVOICE_TEXT ADD CONSTRAINT INVOICE_TEXT_PK PRIMARY KEY (INVOICE_TEXT_ID);
ALTER TABLE INVOICE_TEXT ADD CONSTRAINT INVOICE_TEXT_FK1 FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (INVOICE_ID);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.39', 'JMS.01.38');