-- AseType
UPDATE SYSTEM_FUNCTION SET NAME='/findAseType', DESCRIPTION='View all AseType' WHERE SYSTEM_FUNCTION_ID=240;
UPDATE SYSTEM_FUNCTION SET NAME='/viewAseType', DESCRIPTION='View AseType details' WHERE SYSTEM_FUNCTION_ID=241;
UPDATE SYSTEM_FUNCTION SET NAME='/editAseType', DESCRIPTION='Edit AseType details' WHERE SYSTEM_FUNCTION_ID=242;
-- AseConnType
UPDATE SYSTEM_FUNCTION SET NAME='/findAseConnType', DESCRIPTION='View all AseConnType' WHERE SYSTEM_FUNCTION_ID=250;
UPDATE SYSTEM_FUNCTION SET NAME='/viewAseConnType', DESCRIPTION='View AseConnType details' WHERE SYSTEM_FUNCTION_ID=251;
UPDATE SYSTEM_FUNCTION SET NAME='/editAseConnType', DESCRIPTION='Edit AseConnType details' WHERE SYSTEM_FUNCTION_ID=252;

UPDATE SYSTEM_FUNCTION SET NAME='/editFcaAse', DESCRIPTION='Edit File FcaAse details' WHERE SYSTEM_FUNCTION_ID=1103;
UPDATE SYSTEM_FUNCTION SET NAME='/findAseChange', DESCRIPTION='Find File AseChange details' WHERE SYSTEM_FUNCTION_ID=1114;
UPDATE SYSTEM_FUNCTION SET NAME='/viewAseChange', DESCRIPTION='View File AseChange details' WHERE SYSTEM_FUNCTION_ID=1115;
UPDATE SYSTEM_FUNCTION SET NAME='/calendarAseChange', DESCRIPTION='Monthly AseChange Calendar' WHERE SYSTEM_FUNCTION_ID=1116;
UPDATE SYSTEM_FUNCTION SET NAME='/editAseChange', DESCRIPTION='Edit File AseChange details' WHERE SYSTEM_FUNCTION_ID=1117;

INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES (1119, '/file', '/downloadFileDoc', 'Download File FileDoc');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (2, 1119);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.01', 'JMS.01.00');