-- UI access
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1146, '/file', '/fileArchive', 'Archiving Register');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 1146);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (2, 1146);

-- DROP TABLE ARCHIVE;
CREATE TABLE ARCHIVE (
    ARCHIVE_ID numeric(11, 0) IDENTITY NOT NULL,
    BOX_CODE varchar(32) NOT NULL,
    BOX_NAME varchar(50) NOT NULL,
    BOX_LOCATION varchar(255) NULL,
    BOX_DESCRIPTION varchar(512) NULL,
    DATE_FROM datetime NOT NULL,
    DATE_TO datetime NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ARCHIVE ADD CONSTRAINT ARCHIVE_PK PRIMARY KEY (ARCHIVE_ID);
ALTER TABLE ARCHIVE ADD CONSTRAINT ARCHIVE_UK1 UNIQUE (BOX_CODE);

-- DROP TABLE FILE_ARCHIVE;
CREATE TABLE FILE_ARCHIVE (
    FILE_ID numeric(11, 0) NOT NULL,
    ARCHIVE_ID numeric(11, 0) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE FILE_ARCHIVE ADD CONSTRAINT FILE_ARCHIVE_PK PRIMARY KEY (FILE_ID);
ALTER TABLE FILE_ARCHIVE ADD CONSTRAINT FILE_ARCHIVE_FK1 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID);
ALTER TABLE FILE_ARCHIVE ADD CONSTRAINT FILE_ARCHIVE_FK2 FOREIGN KEY (ARCHIVE_ID) REFERENCES ARCHIVE (ARCHIVE_ID);

INSERT INTO FILE_STATUS (FILE_STATUS_ID, NAME) VALUES (3, 'Archived');

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.28', 'JMS.01.27');