-- ALTER TABLE KEY_REG ADD CONTACT_ID numeric(11, 0) NULL;
-- ALTER TABLE KEY_REG ADD CONSTRAINT KEY_REG_FK2 FOREIGN KEY(CONTACT_ID) REFERENCES CONTACT(CONTACT_ID);

-- 5.3.17. Job Creation/Allocation for Individuals :: WIP
ALTER TABLE JOBS ADD RESPONSIBLE_USER_ID numeric(11, 0) NULL;
ALTER TABLE JOBS ADD CONSTRAINT JOBS_FK5 FOREIGN KEY (RESPONSIBLE_USER_ID) REFERENCES USERS (USER_ID);

CREATE TABLE USERS_WORKGROUP (
	USER_ID numeric(11, 0) NOT NULL,
	WORK_GROUP_ID numeric(11, 0) NOT NULL
);
ALTER TABLE USERS_WORKGROUP ADD CONSTRAINT USERS_WORKGROUP_PK PRIMARY KEY (USER_ID, WORK_GROUP_ID);

ALTER TABLE USERS_WORKGROUP ADD CONSTRAINT USERS_WORKGROUP_FK1 FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE USERS_WORKGROUP ADD CONSTRAINT USERS_WORKGROUP_FK2 FOREIGN KEY (WORK_GROUP_ID) REFERENCES WORK_GROUP (WORK_GROUP_ID);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.07', 'JMS.01.06');