ALTER TABLE BUILDING DROP COLUMN ADDITIONAL_NOTES;
ALTER TABLE BUILDING ALTER COLUMN DESCRIPTION varchar(1024) NULL;
ALTER TABLE BUILDING ALTER COLUMN USAGE varchar(1024) NULL;

INSERT INTO SALUTATION (SALUTATION) VALUES ('-');

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.09', 'JMS.01.08');