-- Owner Extension
-- OwnerType
CREATE TABLE OWNER_TYPE (
    OWNER_TYPE_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE OWNER_TYPE ADD CONSTRAINT OWNER_TYPE_PK PRIMARY KEY (OWNER_TYPE_ID);

INSERT INTO OWNER_TYPE (OWNER_TYPE_ID, NAME, CREATED_BY) VALUES (1, 'Owner', 10001);
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID, NAME, CREATED_BY) VALUES (2, 'Body Corporate', 10001);
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID, NAME, CREATED_BY) VALUES (3, 'Property Manager', 10001);
INSERT INTO OWNER_TYPE (OWNER_TYPE_ID, NAME, CREATED_BY) VALUES (4, 'Tenant', 10001);

ALTER TABLE OWNER ADD OWNER_TYPE_ID numeric(11,0) NULL;
UPDATE OWNER SET OWNER_TYPE_ID = 1;
ALTER TABLE OWNER ALTER COLUMN OWNER_TYPE_ID numeric(11,0) NOT NULL;
ALTER TABLE OWNER ADD CONSTRAINT OWNER_FK6 FOREIGN KEY (OWNER_TYPE_ID) REFERENCES OWNER_TYPE (OWNER_TYPE_ID);

ALTER TABLE OWNER ADD ABN varchar(20) NULL;
ALTER TABLE OWNER ADD REFERENCE varchar(20) NULL;
ALTER TABLE OWNER ADD DEFAULT_CONTACT char(1) NOT NULL DEFAULT 'N';
UPDATE OWNER SET DEFAULT_CONTACT = 'Y';

ALTER TABLE OWNER ADD CONSTRAINT OWNER_UK1 UNIQUE (FILE_ID, OWNER_TYPE_ID);

-- Action for Individuals
ALTER TABLE FILE_ACTION ADD RESPONSIBLE_USER_ID numeric(11, 0) NULL;
ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_FK6 FOREIGN KEY (RESPONSIBLE_USER_ID) REFERENCES USERS (USER_ID);

ALTER TABLE JOB_ACTION ADD RESPONSIBLE_USER_ID numeric(11, 0) NULL;
ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_FK6 FOREIGN KEY (RESPONSIBLE_USER_ID) REFERENCES USERS (USER_ID);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.15', 'JMS.01.14');