-- MailRegister
-- UI access
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1141, '/file', '/mailRegister', 'Mail Register');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, QUERY, NAME, DESCRIPTION)
 VALUES (1142, '/file', '/mailRegister', 'parameter=export', 'Mail Register :: Export');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (2, 1141);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (3, 1141);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (4, 1141);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (5, 1141);

-- MailType
-- DROP TABLE MAIL_TYPE
CREATE TABLE MAIL_TYPE (
    MAIL_TYPE_ID numeric(11, 0) IDENTITY NOT NULL,
    NAME varchar(50) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE MAIL_TYPE ADD CONSTRAINT MAIL_TYPE_PK PRIMARY KEY (MAIL_TYPE_ID);

INSERT INTO MAIL_TYPE (NAME) VALUES ('Standard');

-- FileType
INSERT INTO FILE_TYPE (FILE_TYPE_ID, NAME) VALUES (2, 'Mail Register');

-- MailRegister
-- DROP TABLE MAIL_REGISTER
CREATE TABLE MAIL_REGISTER (
    MAIL_REGISTER_ID numeric(11, 0) NOT NULL,
	FILE_ID numeric(11, 0) NOT NULL,
    MAIL_TYPE_ID numeric(11) NULL,
    MAIL_REGISTER_DATE datetime NOT NULL,
    MAIL_REGISTER_NO varchar(50) NULL,
    MAIL_REGISTER_DETAILS varchar(512) NULL,
    MAIL_IN char(1) NOT NULL DEFAULT 'Y',
    RTS char(1) NOT NULL DEFAULT 'N',
    FROM_CONTACT_ID numeric(11,0) NULL,
    FROM_ADDRESS_ID numeric(11,0) NULL,
    TO_CONTACT_ID numeric(11,0) NULL,
    TO_ADDRESS_ID numeric(11,0) NULL,
    DOCUMENT_ID numeric(11,0) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_PK PRIMARY KEY (MAIL_REGISTER_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK1 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID)
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK2 FOREIGN KEY (MAIL_TYPE_ID) REFERENCES MAIL_TYPE (MAIL_TYPE_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK3 FOREIGN KEY (FROM_CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK4 FOREIGN KEY (FROM_ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK5 FOREIGN KEY (TO_CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK6 FOREIGN KEY (TO_ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK7 FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.19', 'JMS.01.18');