ALTER TABLE MAIL_REGISTER ADD FILE_ACTION_ID numeric(11,0) NULL;
ALTER TABLE MAIL_REGISTER ADD JOB_ACTION_ID numeric(11,0) NULL;

ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK7 FOREIGN KEY (FILE_ACTION_ID) REFERENCES FILE_ACTION (FILE_ACTION_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK8 FOREIGN KEY (JOB_ACTION_ID) REFERENCES JOB_ACTION (JOB_ACTION_ID);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.21', 'JMS.01.20');