-- 5.3.12. Staff Management Calendar & Functions

-- UI access
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (14, '/user', '/calendarStaff', 'Staff Management Calendar & Functions');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (15, '/user', '/calendarStaffSupervisor', 'Staff Management Calendar & Functions Supervisor', 'Y');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (2, 14);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (3, 14);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (4, 14);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (5, 14);

-- Status
CREATE TABLE LEAVE_STATUS (
    LEAVE_STATUS_ID numeric(11, 0) IDENTITY NOT NULL,
    NAME varchar(50) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE LEAVE_STATUS ADD CONSTRAINT LEAVE_STATUS_PK PRIMARY KEY (LEAVE_STATUS_ID);

INSERT INTO LEAVE_STATUS (NAME, CREATED_BY) VALUES ('Submitted', 10001);
INSERT INTO LEAVE_STATUS (NAME, CREATED_BY) VALUES ('Approved', 10001);
INSERT INTO LEAVE_STATUS (NAME, CREATED_BY) VALUES ('Declined', 10001);

-- LeaveType
CREATE TABLE LEAVE_TYPE (
    LEAVE_TYPE_ID numeric(11, 0) IDENTITY NOT NULL,
    NAME varchar(50) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE LEAVE_TYPE ADD CONSTRAINT LEAVE_TYPE_PK PRIMARY KEY (LEAVE_TYPE_ID);

INSERT INTO LEAVE_TYPE (NAME, CREATED_BY) VALUES ('Annual Leave', 10001);
INSERT INTO LEAVE_TYPE (NAME, CREATED_BY) VALUES ('Carers Leave Unpaid', 10001);
INSERT INTO LEAVE_TYPE (NAME, CREATED_BY) VALUES ('Jury Duty', 10001);
INSERT INTO LEAVE_TYPE (NAME, CREATED_BY) VALUES ('Leave Without Pay', 10001);
INSERT INTO LEAVE_TYPE (NAME, CREATED_BY) VALUES ('Personal/Carers Leave Paid', 10001);
INSERT INTO LEAVE_TYPE (NAME, CREATED_BY) VALUES ('Study & Exam Leave', 10001);
INSERT INTO LEAVE_TYPE (NAME, CREATED_BY) VALUES ('Time in Lieu', 10001);

INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (333, '/setup', '/findLeaveType', 'View all Leave Type');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (334, '/setup', '/viewLeaveType', 'View Leave Type details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (335, '/setup', '/editLeaveType', 'Edit Leave Type details');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 333);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 334);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 335);

-- STATUS_ID - java enum for now
CREATE TABLE STAFF_LEAVE (
    STAFF_LEAVE_ID numeric(11, 0) IDENTITY NOT NULL,
    USER_ID numeric(11, 0) NOT NULL,
    LEAVE_GROUP_ID numeric(11, 0) NOT NULL,
    LEAVE_TYPE_ID numeric(11, 0) NOT NULL,
    LEAVE_DATE date NOT NULL,
    DESCRIPTION varchar(255) NULL,
    STATUS_ID numeric(11, 0) NULL,
    STATUS_BY numeric(11,0),
    STATUS_DATE datetime,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE STAFF_LEAVE ADD CONSTRAINT STAFF_LEAVE_PK PRIMARY KEY (STAFF_LEAVE_ID);

ALTER TABLE STAFF_LEAVE ADD CONSTRAINT STAFF_LEAVE_FK1 FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);
ALTER TABLE STAFF_LEAVE ADD CONSTRAINT STAFF_LEAVE_FK2 FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES LEAVE_TYPE (LEAVE_TYPE_ID);
ALTER TABLE STAFF_LEAVE ADD CONSTRAINT STAFF_LEAVE_FK3 FOREIGN KEY (STATUS_ID) REFERENCES LEAVE_STATUS (LEAVE_STATUS_ID);
ALTER TABLE STAFF_LEAVE ADD CONSTRAINT STAFF_LEAVE_UK1 UNIQUE (USER_ID, LEAVE_DATE);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.12', 'JMS.01.11');