-- 5.3.6. Call Taking Storage and Reporting
-- UI access
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1137, '/file', '/findCall', 'Call Taking Storage and Reporting');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1138, '/file', '/exportCall', 'Call Taking Storage and Reporting :: Export');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (2, 1137);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (3, 1137);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (4, 1137);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (5, 1137);

ALTER TABLE FILE_ACTION ADD CONTACT_ID numeric(11,0) NULL;
ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_FK5 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);

ALTER TABLE JOB_ACTION ADD CONTACT_ID numeric(11,0) NULL;
ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_FK5 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);

-- default 7h15m (TODO: DROP CONSTRAINT manually)
UPDATE STAFF_LEAVE SET LEAVE_TAKEN = 7.25;
-- ALTER TABLE STAFF_LEAVE	DROP CONSTRAINT DF__STAFF_LEA__LEAVE__24B26D99;
ALTER TABLE STAFF_LEAVE ADD CONSTRAINT STAFF_LEAVE_DF1 DEFAULT ((7.25)) FOR LEAVE_TAKEN;

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.14', 'JMS.01.13');