ALTER TABLE ACTION_CODE ADD JOB_TYPE_ID numeric(11, 0) NULL;
ALTER TABLE ACTION_CODE ADD CONSTRAINT ACTION_CODE_FK5 FOREIGN KEY (JOB_TYPE_ID) REFERENCES JOB_TYPE (JOB_TYPE_ID);

ALTER TABLE FILE_ACTION ADD PARENT_ACTION_ID numeric(11, 0) NULL;
ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_FK7 FOREIGN KEY (PARENT_ACTION_ID) REFERENCES FILE_ACTION (FILE_ACTION_ID);

ALTER TABLE FILE_ACTION ADD PARENT_JOB_ACTION_ID numeric(11, 0) NULL;
ALTER TABLE FILE_ACTION ADD CONSTRAINT FILE_ACTION_FK8 FOREIGN KEY (PARENT_JOB_ACTION_ID) REFERENCES JOB_ACTION (JOB_ACTION_ID);

ALTER TABLE JOB_ACTION ADD PARENT_ACTION_ID numeric(11, 0) NULL;
ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_FK7 FOREIGN KEY (PARENT_ACTION_ID) REFERENCES JOB_ACTION (JOB_ACTION_ID);

ALTER TABLE JOB_ACTION ADD PARENT_FILE_ACTION_ID numeric(11, 0) NULL;
ALTER TABLE JOB_ACTION ADD CONSTRAINT JOB_ACTION_FK8 FOREIGN KEY (PARENT_FILE_ACTION_ID) REFERENCES FILE_ACTION (FILE_ACTION_ID);

INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.46', 'JMS.01.45');