ALTER TABLE SYSTEM_FUNCTION ADD LOGICAL CHAR(1) NULL;

INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1120, '/file', '/viewOwner', 'View File Owner details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1121, '/file', '/viewFcaAse', 'View File FcaAse details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1122, '/file', '/viewStationKey', 'View File Station/Keys details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1123, '/file', '/viewAlarmPanel', 'View File AlarmPanel details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1124, '/file', '/viewBuilding', 'View File Building details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1125, '/file', '/viewCrmActionsToDo', 'View CRM Actions ToDo', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1126, '/file', '/viewCrmCompletedActions', 'View CRM Completed Actions', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1127, '/file', '/viewJobActionsToDo', 'View Job Actions ToDo', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1128, '/file', '/viewJobCompletedActions', 'View Job Completed Actions', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1129, '/file', '/viewFileDocChkList', 'View File FileDocChkList details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1130, '/file', '/viewFileDoc', 'View File FileDoc details', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1131, '/file', '/viewStakeholder', 'View File Stakeholders', 'Y');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1132, '/file', '/viewSapBilling', 'View File SapBilling details', 'Y');

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.02', 'JMS.01.01');