-- UI access
-- www.toadworld.com/Downloads/FreewareandTrials/ToadforSQLServerFreeware/tabid/562/Default.aspx
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (336, '/setup', '/mailType', 'Mail Type');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 336);

-- MailRegister
DROP TABLE MAIL_REGISTER;

CREATE TABLE MAIL_REGISTER (
    MAIL_REGISTER_ID numeric(11, 0) IDENTITY NOT NULL,
	FILE_ID numeric(11, 0) NOT NULL,
    MAIL_TYPE_ID numeric(11) NULL,
    MAIL_REGISTER_DATE datetime NOT NULL,
    MAIL_REGISTER_NO varchar(50) NULL,
    MAIL_REGISTER_DETAILS varchar(512) NULL,
    MAIL_IN char(1) NOT NULL DEFAULT 'Y',
    RTS char(1) NOT NULL DEFAULT 'N',
    CONTACT_ID numeric(11,0) NULL,
    ADDRESS_ID numeric(11,0) NULL,
    WORK_GROUP_ID numeric(11,0) NULL,
    USER_ID numeric(11,0) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_PK PRIMARY KEY (MAIL_REGISTER_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK1 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID)
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK2 FOREIGN KEY (MAIL_TYPE_ID) REFERENCES MAIL_TYPE (MAIL_TYPE_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK3 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK4 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK5 FOREIGN KEY (WORK_GROUP_ID) REFERENCES WORK_GROUP (WORK_GROUP_ID);
ALTER TABLE MAIL_REGISTER ADD CONSTRAINT MAIL_REGISTER_FK6 FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.20', 'JMS.01.19');