IF EXISTS (SELECT name FROM sys.objects WHERE name = N'INVOICE_TEXT' AND type = N'U')
    DROP TABLE INVOICE_TEXT
GO
IF EXISTS (SELECT name FROM sys.objects WHERE name = N'INVOICE_GL_DATA' AND type = N'U')
    DROP TABLE INVOICE_GL_DATA
GO
IF EXISTS (SELECT name FROM sys.objects WHERE name = N'INVOICE_DATA' AND type = N'U')
    DROP TABLE INVOICE_DATA
GO
IF EXISTS (SELECT name FROM sys.objects WHERE name = N'INVOICE_HEADER' AND type = N'U')
    DROP TABLE INVOICE_HEADER
GO
IF EXISTS (SELECT name FROM sys.objects WHERE name = N'INVOICE' AND type = N'U')
    DROP TABLE INVOICE
GO
IF EXISTS (SELECT name FROM sys.objects WHERE name = N'INVOICE_BATCH' AND type = N'U')
    DROP TABLE INVOICE_BATCH
GO
IF EXISTS (SELECT name FROM sys.objects WHERE name = N'INVOICE_TYPE' AND type = N'U')
    DROP TABLE INVOICE_TYPE
GO
IF EXISTS (SELECT name FROM sys.objects WHERE name = N'INVOICE_AREA' AND type = N'U')
    DROP TABLE INVOICE_AREA
GO
IF EXISTS (SELECT name FROM sys.objects WHERE name = N'BRIGADE' AND type = N'U')
    DROP TABLE BRIGADE
GO