-- 5.3.12. Staff Management Calendar & Functions
ALTER TABLE STAFF_LEAVE ADD LEAVE_TAKEN numeric(3, 2) NOT NULL DEFAULT 1.00;
ALTER TABLE STAFF_LEAVE ADD FORM_RECEIVED char(1) NOT NULL DEFAULT 'N';
ALTER TABLE STAFF_LEAVE ADD FORM_SENT_HR_DATE datetime NULL;

CREATE TABLE BUILDING_BCLASSIFICATION (
    BUILDING_ID numeric(11,0) NOT NULL,
    BUILDING_CLASSIFICATION_ID numeric(11,0) NOT NULL
);
ALTER TABLE BUILDING_BCLASSIFICATION ADD CONSTRAINT BUILDING_BCLASSIFICATION_PK PRIMARY KEY (BUILDING_ID, BUILDING_CLASSIFICATION_ID);

ALTER TABLE BUILDING_BCLASSIFICATION ADD CONSTRAINT BUILDING_BCLASSIFICATION_FK1 FOREIGN KEY (BUILDING_ID) REFERENCES BUILDING (BUILDING_ID);
ALTER TABLE BUILDING_BCLASSIFICATION ADD CONSTRAINT BUILDING_BCLASSIFICATION_FK2 FOREIGN KEY (BUILDING_CLASSIFICATION_ID) REFERENCES BUILDING_CLASSIFICATION (BUILDING_CLASSIFICATION_ID);

ALTER TABLE BUILDING DROP CONSTRAINT BUILDING_FK5;
ALTER TABLE BUILDING DROP COLUMN BUILDING_CLASSIFICATION_ID;

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.13', 'JMS.01.12');