-- ALTER TABLE KEY_REG ADD CONTACT_ID numeric(11, 0) NULL;
-- ALTER TABLE KEY_REG ADD CONSTRAINT KEY_REG_FK2 FOREIGN KEY(CONTACT_ID) REFERENCES CONTACT(CONTACT_ID);

-- 5.3.24. Building Classification
CREATE TABLE BUILDING_CLASSIFICATION (
    BUILDING_CLASSIFICATION_ID numeric(11, 0) IDENTITY NOT NULL,
    NAME varchar(50) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE BUILDING_CLASSIFICATION ADD CONSTRAINT BUILDING_CLASSIFICATION_PK PRIMARY KEY (BUILDING_CLASSIFICATION_ID);

ALTER TABLE BUILDING ADD BUILDING_CLASSIFICATION_ID numeric(11, 0) NULL;
ALTER TABLE BUILDING ADD CONSTRAINT BUILDING_FK5 FOREIGN KEY (BUILDING_CLASSIFICATION_ID) REFERENCES BUILDING_CLASSIFICATION (BUILDING_CLASSIFICATION_ID);
ALTER TABLE BUILDING ADD ADDITIONAL_NOTES varchar(1024) NULL;

-- BuildingClassification
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (320, '/setup', '/findBuildingClassification', 'View all Building Classification');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (321, '/setup', '/viewBuildingClassification', 'View Building Classification details');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION) VALUES
 (322, '/setup', '/editBuildingClassification', 'Edit Building Classification details');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 320);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 321);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 322);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.08', 'JMS.01.07');