-- ASE Key
-- UI access
UPDATE SYSTEM_FUNCTION SET NAME = '/aseKey' WHERE SYSTEM_FUNCTION_ID = 1139;
UPDATE SYSTEM_FUNCTION SET NAME = '/aseKey', QUERY = 'parameter=export' WHERE SYSTEM_FUNCTION_ID = 1140;

-- DELETE ASE_KEY CHANGES FROM PREVIOUS SCRIPT
ALTER TABLE ASE_FILE DROP CONSTRAINT ASE_FILE_FK3;
ALTER TABLE ASE_FILE DROP CONSTRAINT ASE_FILE_FK4;
ALTER TABLE ASE_FILE DROP COLUMN CONTACT_ID;
ALTER TABLE ASE_FILE DROP COLUMN SENT_ADT_DATE;
ALTER TABLE ASE_FILE DROP COLUMN SENT_CUSTOMER_DATE;
ALTER TABLE ASE_FILE DROP COLUMN SENT_METHOD_ID;
ALTER TABLE ASE_FILE DROP COLUMN SENT_REFERENCE_NO;
ALTER TABLE ASE_FILE DROP COLUMN PAYMENT_METHOD_ID;
ALTER TABLE ASE_FILE DROP COLUMN INVOICE_ID;

-- ASE Key
CREATE TABLE ASE_KEY (
    ASE_KEY_ID numeric(11, 0) NOT NULL,
    FILE_ID numeric(11, 0) NOT NULL,
    ASE_KEY_NO varchar(50) NOT NULL,
    SUPPLIER_ID numeric(11,0) NULL,
    SENT_ADT_DATE datetime NULL,
    SENT_CUSTOMER_DATE datetime NULL,
    SENT_METHOD_ID numeric(11) NULL,
    SENT_REFERENCE_NO varchar(20) NULL,
    PAYMENT_METHOD_ID numeric(11) NULL,
    INVOICE_ID numeric(11) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_PK PRIMARY KEY (ASE_KEY_ID);
ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_FK1 FOREIGN KEY (FILE_ID) REFERENCES FILES (FILE_ID)
ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_FK2 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID);
-- ase key invoice - will be renamed to ASE_KEY_INVOICE in JMS.01.39.sql
ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_FK3 FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (INVOICE_ID);

-- FileType
CREATE TABLE FILE_TYPE (
    FILE_TYPE_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE FILE_TYPE ADD CONSTRAINT FILE_TYPE_PK PRIMARY KEY (FILE_TYPE_ID);

ALTER TABLE FILES ADD FILE_TYPE_ID numeric(11,0) NULL;
-- mssql error 20 ???
-- ALTER TABLE FILES ADD CONSTRAINT FILES_FK4 FOREIGN KEY (FILE_TYPE_ID) REFERENCES FILE_TYPE (FILE_TYPE_ID);

INSERT INTO FILE_TYPE (FILE_TYPE_ID, NAME) VALUES (1, 'ASE Key');

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.17', 'JMS.01.16');