ALTER TABLE INVOICE_DATA DROP CONSTRAINT INVOICE_DATA_FK2;
ALTER TABLE INVOICE_GL_DATA DROP CONSTRAINT INVOICE_GL_DATA_FK2;

sp_rename 'INVOICE_DATA.FCA_NO', 'ASSIGNMENT';
sp_rename 'INVOICE_GL_DATA.FCA_NO', 'ASSIGNMENT';

ALTER TABLE INVOICE_DATA ALTER COLUMN ASSIGNMENT varchar(50) NULL;
ALTER TABLE INVOICE_GL_DATA ALTER COLUMN ASSIGNMENT varchar(50) NULL;

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.45', 'JMS.01.44');