CREATE INDEX ACTION_CODE_IDX1 ON ACTION_CODE (WORK_GROUP_ID);

CREATE INDEX FILES_IDX1 ON FILES (FILE_TYPE_ID);
CREATE INDEX FILES_IDX2 ON FILES (FILE_STATUS_ID);

CREATE INDEX FCA_IDX2 ON FCA (FILE_ID);

CREATE INDEX OWNER_IDX1 ON OWNER (OWNER_TYPE_ID);
CREATE INDEX OWNER_IDX2 ON OWNER (FILE_ID);
CREATE INDEX OWNER_IDX3 ON OWNER (CONTACT_ID);

CREATE INDEX BUILDING_IDX1 ON BUILDING (FILE_ID);
CREATE INDEX BUILDING_IDX2 ON BUILDING (ADDRESS_ID);

CREATE INDEX FILE_ACTION_IDX1 ON FILE_ACTION (FILE_ID);
CREATE INDEX FILE_ACTION_IDX2 ON FILE_ACTION (ACTION_CODE_ID);
CREATE INDEX FILE_ACTION_IDX3 ON FILE_ACTION (CONTACT_ID);
CREATE INDEX FILE_ACTION_IDX4 ON FILE_ACTION (RESPONSIBLE_USER_ID);

CREATE INDEX JOBS_IDX1 ON JOBS (STATUS);
CREATE INDEX JOBS_IDX2 ON JOBS (JOB_TYPE_ID);
CREATE INDEX JOBS_IDX3 ON JOBS (FILE_ID);
CREATE INDEX JOBS_IDX4 ON JOBS (FCA_NO);
CREATE INDEX JOBS_IDX5 ON JOBS (RESPONSIBLE_USER_ID);

CREATE INDEX JOB_ACTION_IDX1 ON JOB_ACTION (JOB_ID);
CREATE INDEX JOB_ACTION_IDX2 ON JOB_ACTION (ACTION_CODE_ID);
CREATE INDEX JOB_ACTION_IDX3 ON JOB_ACTION (CONTACT_ID);
CREATE INDEX JOB_ACTION_IDX4 ON JOB_ACTION (RESPONSIBLE_USER_ID);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.23', 'JMS.01.22');