-- UI access
UPDATE SYSTEM_FUNCTION SET NAME = '/scheduledTask', DESCRIPTION = 'Scheduled Task' WHERE SYSTEM_FUNCTION_ID = 337;

INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (338, '/setup', '/systemFunction', 'System Function');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 338);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.25', 'JMS.01.24');