-- UI access
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (337, '/setup', '/scheduledTask', 'Scheduled Task');
-- UPDATE SYSTEM_FUNCTION SET NAME = '/scheduledTask', DESCRIPTION = 'Scheduled Task' WHERE SYSTEM_FUNCTION_ID = 337;
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 337);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (2, 337);
-- UI access
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1145, '/file', '/isolation', 'Isolation History', 'Y');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (1, 1145);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (2, 1145);

-- ScheduledTask
-- DROP TABLE SCHEDULED_TASK;
CREATE TABLE SCHEDULED_TASK (
    SCHEDULED_TASK_ID numeric(11, 0) IDENTITY NOT NULL,
    TASK_NAME varchar(50) NULL,
    REQUEST varchar(512) NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE SCHEDULED_TASK ADD CONSTRAINT SCHEDULED_TASK_PK PRIMARY KEY (SCHEDULED_TASK_ID);
-- ALTER TABLE SCHEDULED_TASK ADD CONSTRAINT SCHEDULED_TASK_DF1 DEFAULT (('Y')) FOR ACTIVE;

-- 
-- ScheduledTaskHistory
-- DROP TABLE SCHEDULED_TASK;
CREATE TABLE SCHEDULED_TASK_HISTORY (
    SCHEDULED_TASK_HISTORY_ID numeric(11, 0) IDENTITY NOT NULL,
    SCHEDULED_TASK_ID numeric(11, 0) NOT NULL,
    TASK_NAME varchar(50) NULL,
    REQUEST varchar(512) NULL,
    RESPONSE varchar(512) NULL,
    STATUS char(1) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE SCHEDULED_TASK_HISTORY ADD CONSTRAINT SCHEDULED_TASK_HISTORY_PK PRIMARY KEY (SCHEDULED_TASK_HISTORY_ID);
ALTER TABLE SCHEDULED_TASK_HISTORY ADD CONSTRAINT SCHEDULED_TASK_HISTORY_FK1 FOREIGN KEY (SCHEDULED_TASK_ID) REFERENCES SCHEDULED_TASK (SCHEDULED_TASK_ID);

-- IsolationHistory
-- DROP TABLE ISOLATION_HISTORY;
CREATE TABLE ISOLATION_HISTORY (
    ISOLATION_HISTORY_ID numeric(11, 0) IDENTITY NOT NULL,
    FCA_NO varchar(8) NOT NULL,
    CS_NUMBER varchar(32) NULL,
    ISOLATION_DATE datetime NOT NULL,
    DE_ISOLATION_DATE datetime NOT NULL,
    INPUT numeric(3,0) NOT NULL,
    DETAILS varchar(512) NULL,
    KEY_DETAILS varchar(512) NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE ISOLATION_HISTORY ADD CONSTRAINT ISOLATION_HISTORY_PK PRIMARY KEY (ISOLATION_HISTORY_ID);
ALTER TABLE ISOLATION_HISTORY ADD CONSTRAINT ISOLATION_HISTORY_FK1 FOREIGN KEY (FCA_NO) REFERENCES FCA (FCA_NO);
CREATE INDEX ISOLATION_HISTORY_IDX1 ON ISOLATION_HISTORY (FCA_NO);
CREATE INDEX ISOLATION_HISTORY_IDX2 ON ISOLATION_HISTORY (FCA_NO, INPUT, ISOLATION_DATE, DE_ISOLATION_DATE);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.24', 'JMS.01.23');