-- 5.3.4. Customer Enquiries
-- UI access
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1143, '/file', '/enquiry', 'Customer Enquiries');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, QUERY, DESCRIPTION)
 VALUES (1144, '/file', '/enquiry', 'parameter=export', 'Customer Enquiries :: Export');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (2, 1143);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (3, 1143);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (4, 1143);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (5, 1143);

UPDATE SYSTEM_FUNCTION SET NAME = '/mailRegister', QUERY = 'parameter=export' WHERE SYSTEM_FUNCTION_ID = 1142;

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.22', 'JMS.01.21');