-- ASE Key
-- UI access
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1139, '/file', '/findAseFile', 'ASE Keys');
INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, QUERY, NAME, DESCRIPTION)
 VALUES (1140, '/file', '/findAseFile', 'parameter=export', 'ASE Keys :: Export');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (2, 1139);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (3, 1139);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (4, 1139);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (5, 1139);

ALTER TABLE ASE_FILE ADD CONTACT_ID numeric(11,0) NULL;
ALTER TABLE ASE_FILE ADD CONSTRAINT ASE_FILE_FK3 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);

-- ase key invoice - will be renamed to ASE_KEY_INVOICE in JMS.01.39.sql
CREATE TABLE INVOICE (
    INVOICE_ID numeric(11, 0) identity(10001,1) NOT NULL,
    INVOICE_NO varchar(20) NULL,
    INVOICE_DATE datetime NULL,
    INVOICE_AMOUNT decimal(19,2) NULL,
    AUTHORISED_BY numeric(11, 0) NULL,
    AUTHORISED_DATE datetime NULL,
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_PK PRIMARY KEY (INVOICE_ID);
ALTER TABLE INVOICE ADD CONSTRAINT INVOICE_FK1 FOREIGN KEY (AUTHORISED_BY) REFERENCES USERS (USER_ID);

ALTER TABLE ASE_FILE ADD SENT_ADT_DATE datetime NULL;
ALTER TABLE ASE_FILE ADD SENT_CUSTOMER_DATE datetime NULL;
ALTER TABLE ASE_FILE ADD SENT_METHOD_ID numeric(11) NULL;
ALTER TABLE ASE_FILE ADD SENT_REFERENCE_NO varchar(20) NULL;
ALTER TABLE ASE_FILE ADD PAYMENT_METHOD_ID numeric(11) NULL;

ALTER TABLE ASE_FILE ADD INVOICE_ID numeric(11) NULL;
ALTER TABLE ASE_FILE ADD CONSTRAINT ASE_FILE_FK4 FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (INVOICE_ID);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.16', 'JMS.01.15');