INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION, LOGICAL)
 VALUES (1133, '/file', '/viewEmergencyContact', 'View File Emergency Contact details', 'Y');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (2, 1133);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (3, 1133);

INSERT INTO SYSTEM_FUNCTION (SYSTEM_FUNCTION_ID, MODULE, NAME, DESCRIPTION)
 VALUES (1134, '/file', '/editEmergencyContact', 'Edit File Emergency Contact details');
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (2, 1134);
INSERT INTO SYSTEM_ACCESS (SECURITY_GROUP_ID, SYSTEM_FUNCTION_ID) VALUES (3, 1134);

--
ALTER TABLE BUILDING_CONTACT ADD PRIORITY int DEFAULT 1 NOT NULL;
ALTER TABLE BUILDING_CONTACT ADD ACTIVE char(1) DEFAULT 'Y' NOT NULL;
ALTER TABLE BUILDING_CONTACT ADD DOCUMENT_ID numeric(11, 0) NULL;
ALTER TABLE BUILDING_CONTACT ADD CONSTRAINT BUILDING_CONTACT_FK4 FOREIGN KEY(DOCUMENT_ID) REFERENCES DOCUMENT(DOCUMENT_ID);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.06', 'JMS.01.05');