--
CREATE TABLE SENT_METHOD (
    SENT_METHOD_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE SENT_METHOD ADD CONSTRAINT SENT_METHOD_PK PRIMARY KEY (SENT_METHOD_ID);

INSERT INTO SENT_METHOD (SENT_METHOD_ID, NAME) VALUES (1, 'Australia Post');
INSERT INTO SENT_METHOD (SENT_METHOD_ID, NAME) VALUES (2, 'Pickup');

--
CREATE TABLE PAYMENT_METHOD (
    PAYMENT_METHOD_ID numeric(11, 0) NOT NULL,
    NAME varchar(50) NOT NULL,
    ACTIVE char(1) NOT NULL DEFAULT 'Y',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE PAYMENT_METHOD ADD CONSTRAINT PAYMENT_METHOD_PK PRIMARY KEY (PAYMENT_METHOD_ID);

INSERT INTO PAYMENT_METHOD (PAYMENT_METHOD_ID, NAME) VALUES (1, 'Credit Card');
INSERT INTO PAYMENT_METHOD (PAYMENT_METHOD_ID, NAME) VALUES (2, 'Purchase Order');
INSERT INTO PAYMENT_METHOD (PAYMENT_METHOD_ID, NAME) VALUES (3, 'Cheque');
INSERT INTO PAYMENT_METHOD (PAYMENT_METHOD_ID, NAME) VALUES (4, 'BPay');

ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_FK4 FOREIGN KEY (SENT_METHOD_ID) REFERENCES SENT_METHOD (SENT_METHOD_ID);
ALTER TABLE ASE_KEY ADD CONSTRAINT ASE_KEY_FK5 FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD (PAYMENT_METHOD_ID);

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('JMS.01.18', 'JMS.01.17');