USE [JMS];

CREATE TABLE UAA_INJURY_TYPE (
    INJURY_TYPE_ID numeric(11,0) identity(1,1) NOT NULL,
	NAME varchar(50) NOT NULL,
    DESCRIPTION varchar(255),
    MULTIPLE char(1) NOT NULL DEFAULT 'N',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE UAA_INJURY_TYPE ADD CONSTRAINT UAA_INJURY_TYPE_PK PRIMARY KEY (INJURY_TYPE_ID);

CREATE TABLE UAA_INJURY (
    INJURY_ID numeric(11,0) identity(10001,1) NOT NULL,
    FIRE_CALL_NO varchar(6) NOT NULL,
    INJURY_NO numeric(2,0),
    INCIDENT_YEAR numeric(4,0) NOT NULL,
    INCIDENT_DATE datetime NULL,
    REGION_ID numeric(11,0) NOT NULL,
    CONTACT_ID numeric(11,0) NOT NULL,
    ADDRESS_ID numeric(11,0),
	INJURY_TYPE_ID numeric(11,0),
	INJURY_TO varchar(15),
	MULTIPLE_INJURY_TYPE_ID numeric(11,0),
	MULTIPLE_INJURY_TO varchar(50),
	ALCOHOL_LEVEL varchar(10),
	DRUGS varchar(25),
	TREATED_AT varchar(40),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_PK PRIMARY KEY (INJURY_ID);

ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_FK1 FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID);
ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_FK2 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_FK3 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID);
ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_FK4 FOREIGN KEY (INJURY_TYPE_ID) REFERENCES UAA_INJURY_TYPE (INJURY_TYPE_ID);
ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_FK5 FOREIGN KEY (MULTIPLE_INJURY_TYPE_ID) REFERENCES UAA_INJURY_TYPE (INJURY_TYPE_ID);

ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_UK1 UNIQUE (FIRE_CALL_NO, INJURY_NO);

--
-- UAA_INJURY_TYPE
--
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES (' Undetermined');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('35 % Burns');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Abrasion');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Back Injury');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Bad');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Broken Ankle');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Burn 1st degree');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Burn 2nd degree');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Burn 3rd degree');
INSERT INTO UAA_INJURY_TYPE (NAME, DESCRIPTION) VALUES ('Burns', 'Burn');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Burns - Not Spec.');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Burns arm, buttocks');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Burns hand, shoulder');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Cardiac Arrest');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Chest Pains');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Contusion');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Contusion to head');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Fracture');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Heart attack');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Heat exhaustion');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Inhalation and burns');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Laceration');
INSERT INTO UAA_INJURY_TYPE (NAME, DESCRIPTION) VALUES ('Minor Burns', 'Minor Burn');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Minor cut to hand.');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Multiple Injuries');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Severe Burns');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Shortness of breath');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('SMOKE  AND ANKLE');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Smoke asphyxiation');
INSERT INTO UAA_INJURY_TYPE (NAME, DESCRIPTION) VALUES ('Smoke Inhalation', 'Smoke Inhilation');
INSERT INTO UAA_INJURY_TYPE (NAME) VALUES ('Smoke, cut arm');

INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('20% flash burns', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('2nd degree Burns', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('3rd Degree burns', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Burn 3rd degree and 2nd degree', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Burn: degree not specified', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('burns', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Burns - degree not specified', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Burns and Smoke inhalation', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Burns Full thickness, Cuts and Contusions,', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Burns to 60% of body+ shock+ smoke inhalation', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('BURNS TO 80% OF BODY', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('burns to both arm and shoulder', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Burns to face, neck, upper arms, left leg.', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Burns to face, shoulder, knee & leg', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Burns to hands', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Burns, smoke inhalation', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('burns20% flash burns', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('CHEST PAINS', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('cut whilst exiting window', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('flash burns 60%', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Full Thickness Burns, Fractures, Cuts, Contusions', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('heat exhaustion', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Heat Stress', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('HIGH BLOOD PREASURE READING AFTER WEARING B.A', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Inhalation and minor burns', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Inhalation burns to lungs, and broken ankle', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Ist degree burns to shoulder and back', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Lacerations', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Lacerations, burns, smoke inhalation', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Lacerations, Smoke Inhalation, Muscle Strain', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Minor burn', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Minor burns to hands', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Minor Burns, Smoke Inhalation & Stab Wounds', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('minor only', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Multiple burns', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Muscle strains', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('not specified in report', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Partial and Superficial Burns', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Severe burns', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('shock', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Smoke and heat', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Smoke Inhalation', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Smoke inhalation and burns', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Smoke Inhalation, Contusions', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Smoke inhalation, minor burns', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Sprains to right knee', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('SUSPECT FRACTURE', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Unknown level of burns and smoke inhalation', 'Y');
INSERT INTO UAA_INJURY_TYPE (NAME, MULTIPLE) VALUES ('Various abrassions', 'Y');

--
-- this should be the last statement in any update script
--
INSERT INTO DBVERSION (DBVERSION, PREV_DBVERSION) VALUES ('UAA.01.03', 'UAA.01.02');