-- login as [jms] default database [JMS]

USE [JMS];

IF EXISTS (SELECT name FROM sys.objects WHERE name = N'UAA_INJURY' AND type = N'U')
    DROP TABLE UAA_INJURY
GO
IF EXISTS (SELECT name FROM sys.objects WHERE name = N'UAA_INJURY_TYPE' AND type = N'U')
    DROP TABLE UAA_INJURY_TYPE
GO

CREATE TABLE UAA_INJURY_TYPE (
    INJURY_TYPE_ID numeric(11,0) identity(1,1) NOT NULL,
	NAME varchar(50) NOT NULL,
    DESCRIPTION varchar(255),
    MULTIPLE char(1) NOT NULL DEFAULT 'N',
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE UAA_INJURY_TYPE ADD CONSTRAINT UAA_INJURY_TYPE_PK PRIMARY KEY (INJURY_TYPE_ID);

CREATE TABLE UAA_INJURY (
    INJURY_ID numeric(11,0) identity(10001,1) NOT NULL,
    FIRE_CALL_NO varchar(6) NOT NULL,
    INJURY_NO numeric(2,0),
    INCIDENT_YEAR numeric(4,0) NOT NULL,
    INCIDENT_DATE datetime NULL,
    REGION_ID numeric(11,0) NOT NULL,
    CONTACT_ID numeric(11,0) NOT NULL,
    ADDRESS_ID numeric(11,0),
	INJURY_TYPE_ID numeric(11,0),
	INJURY_TO varchar(15),
	MULTIPLE_INJURY_TYPE_ID numeric(11,0),
	MULTIPLE_INJURY_TO varchar(50),
	ALCOHOL_LEVEL varchar(10),
	DRUGS varchar(25),
	TREATED_AT varchar(40),
    CREATED_BY numeric(11,0),
    CREATED_DATE datetime NOT NULL DEFAULT getDate(),
    UPDATED_BY numeric(11,0),
    UPDATED_DATE datetime,
    LOCK_VERSION numeric(11, 0) NOT NULL DEFAULT 0
);
ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_PK PRIMARY KEY (INJURY_ID);

ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_FK1 FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID);
ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_FK2 FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (CONTACT_ID);
ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_FK3 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID);
ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_FK4 FOREIGN KEY (INJURY_TYPE_ID) REFERENCES UAA_INJURY_TYPE (INJURY_TYPE_ID);
ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_FK5 FOREIGN KEY (MULTIPLE_INJURY_TYPE_ID) REFERENCES UAA_INJURY_TYPE (INJURY_TYPE_ID);

ALTER TABLE UAA_INJURY ADD CONSTRAINT UAA_INJURY_UK1 UNIQUE (FIRE_CALL_NO, INJURY_NO);
